#!/bin/sh

usage()
{
	echo 1>&2 "Usage: $0 start|stop N"
	exit 1
}

if test "$#" -ne 2; then
	usage
fi

case $1 in
	start)
		ser2net -u -c /etc/ser2net${2}.conf -P /var/run/ser2net${2}.pid;;
	 stop)
		kill `cat /var/run/ser2net${2}.pid`;;
	    *) usage;;
esac


#  -p <controller port> - Start a controller session on the given TCP port
#  -n - Don't detach from the controlling terminal
#  -d - Don't detach and send debug I/O to standard output
#  -u - Disable UUCP locking
