#!/bin/sh

kdb="kdb"

PATH=$PATH:/usr/sbin

_start_or_stop() {
	local start=$1
	[ $start -eq 1 ] && echo -n "Starting " || echo -n "Stopping "
	echo "rs232 over ip"
	eval `${kdb} sls -q sys_pcitbl_`
	nodes=`${kdb} get sys_pcitbl_s${slot}_ifaces`
	for slot in $slots; do
		for dev in [0,1,2,3]; do
			enable=`${kdb} get sys_rs232ip_s${slot}_${dev}_enable`
			[ "$enable" -eq $start ] && _mod_cfg "$slot" "$dev"
		done
	done
}

_node_cfg() {
	local slot=$1
	local dev=$2
	local node=$3

	local lockfile=/var/lock/$node
	local pidfile=/var/run/sercd${node}.pid
	local socat_pidfile=/var/run/socat${node}.pid
	eval `${kdb} sls sys_rs232ip_s${slot}_${dev}_`
	if [ "$enable" -eq 1 ]; then # sercd must be started
		[ -f $lockfile ] && exit 1 # port already used
		if [ -f $pidfile ]; then # sercd already started
			true
		else
			echo -en "\t${node} on ${src_host}:${src_port}"
			sercd -p $src_port -l $src_host -P $pidfile $loglevel /dev/$node $lockfile $poll_interval
		fi
		if [ "$socat_enable" -eq 1 ]; then
			if [ -f $socat_pidfile ]; then
				true
			else
				local socat_str_loglvl=""
				local numlvl=0
				while [ $numlvl -lt $socat_loglevel ]; do
					socat_str_loglvl="${socat_str_loglvl} -d"
					numlvl=`expr $numlvl + 1`
				done
				echo -n " and connect to ${dst_host}:${dst_port}"
				socat -ly -s -P $socat_pidfile $socat_str_loglvl "tcp:${src_host}:${src_port}" "tcp:${dst_host}:${dst_port}"
			fi
		else
			if [ -f $socat_pidfile ]; then
				kill `cat $socat_pidfile`
				rm -f $socat_pidfile
			fi
		fi
		echo ""
	else
		if [ -f $pidfile ]; then
			kill `cat $pidfile`
			rm -f $pidfile
		fi
		if [ -f $socat_pidfile ]; then
			kill `cat $socat_pidfile`
			rm -f $socat_pidfile
		fi
	fi

}

_mod_cfg() {
	local slot=$1
	local dev=$2
	nodes=`kdb get sys_pcitbl_s${slot}_ifaces`
	nodenum=0
	for node in $nodes; do
		if [ -n "$dev" ]; then
			if [ "$dev" -eq "$nodenum" ]; then
				_node_cfg "$slot" "$nodenum" "$node"
				break
			fi
		else
			_node_cfg "$slot" "$nodenum" "$node"
		fi
		nodenum=`expr $nodenum + 1`
	done
}

case "$1" in
	start)
		_start_or_stop 1
		;;
	stop)
		_start_or_stop 0
		;;
	restart)
		_mod_cfg $2 $3
		;;
esac

