/*
 * Automatically generated header file: don't edit
 */

#define AUTOCONF_INCLUDED

/* Version Number */
#define BB_VER "(null)"
#define BB_BT "(null)"

#define CONFIG_DEVEL 1
#define MODULES 1
#define BR2_HAVE_DOT_CONFIG 1
#define BR2_mipsel 1
#define BR2_ARCH "mipsel"
#undef BR2_LINUX_2_4_AR531X
#undef BR2_LINUX_2_6_ARUBA
#undef BR2_LINUX_2_4_BRCM
#undef BR2_LINUX_2_6_BRCM
#undef BR2_LINUX_2_4_AR7
#undef BR2_LINUX_2_4_X86
#undef BR2_LINUX_2_6_X86
#define BR2_LINUX_2_4_ADM5120 1

/*
 * Build options
 */
#define BR2_WGET "wget --passive-ftp -nd"
#undef BR2_TAR_VERBOSITY
#define BR2_JLEVEL 1

/*
 * Toolchain Options
 */

/*
 * uClibc Options
 */
#undef BR2_UCLIBC_VERSION_SNAPSHOT

/*
 * Binutils Options
 */
#undef BR2_BINUTILS_VERSION_2_15_94_0_2
#define BR2_BINUTILS_VERSION_2_16_1 1
#undef BR2_BINUTILS_VERSION_2_16_90_0_3
#undef BR2_BINUTILS_VERSION_2_16_91_0_1
#undef BR2_BINUTILS_VERSION_2_16_91_0_2
#define BR2_BINUTILS_VERSION "2.16.1"

/*
 * Gcc Options
 */
#define BR2_GCC_3_4 1
#define BR2_GCC_VERSION_3_4_4 1
#undef BR2_GCC_VERSION_3_4_5
#undef BR2_GCC_VERSION_4_0_2
#define BR2_GCC_VERSION "3.4.4"
#define BR2_GCC_USE_SJLJ_EXCEPTIONS ""
#define BR2_EXTRA_GCC_CONFIG_OPTIONS ""
#define BR2_INSTALL_LIBSTDCPP 1

/*
 * Common Toolchain Options
 */
#undef BR2_ENABLE_MULTILIB
#define BR2_LARGEFILE 1
#define BR2_TARGET_OPTIMIZATION "-Os -pipe -funit-at-a-time"

/*
 * OpenWrt Package Selection
 */

/*
 * Package categories
 */

/*
 * Base system
 */

/*
 * busybox........................... The Swiss Army Knife of embedded Linux
 */
#define BR2_PACKAGE_BUSYBOX 1
#undef BR2_PACKAGE_BUSYBOX_SNAPSHOT

/*
 * Busybox Configuration
 */
#define BUSYBOX_HAVE_DOT_CONFIG 1

/*
 * General Configuration
 */
#undef BUSYBOX_CONFIG_FEATURE_BUFFERS_USE_MALLOC
#define BUSYBOX_CONFIG_FEATURE_BUFFERS_GO_ON_STACK 1
#undef BUSYBOX_CONFIG_FEATURE_BUFFERS_GO_IN_BSS
#define BUSYBOX_CONFIG_FEATURE_VERBOSE_USAGE 1
#undef BUSYBOX_CONFIG_FEATURE_INSTALLER
#undef BUSYBOX_CONFIG_LOCALE_SUPPORT
#define BUSYBOX_CONFIG_FEATURE_DEVFS 1
#define BUSYBOX_CONFIG_FEATURE_DEVPTS 1
#undef BUSYBOX_CONFIG_FEATURE_CLEAN_UP
#define BUSYBOX_CONFIG_FEATURE_SUID 1
#undef BUSYBOX_CONFIG_FEATURE_SUID_CONFIG
#undef BUSYBOX_CONFIG_SELINUX

/*
 * Build Options
 */
#undef BUSYBOX_CONFIG_STATIC
#define BUSYBOX_CONFIG_LFS 1
#define BUSYBOX_USING_CROSS_COMPILER 1
#define BUSYBOX_CROSS_COMPILER_PREFIX "mipsel-uclibc-"
#define BUSYBOX_EXTRA_CFLAGS_OPTIONS "-Os "

/*
 * Installation Options
 */
#undef BUSYBOX_CONFIG_INSTALL_NO_USR
#define BUSYBOX_PREFIX "./_install"

/*
 * Archival Utilities
 */
#undef BUSYBOX_CONFIG_AR
#define BUSYBOX_CONFIG_BUNZIP2 1
#undef BUSYBOX_CONFIG_CPIO
#undef BUSYBOX_CONFIG_DPKG
#undef BUSYBOX_CONFIG_DPKG_DEB
#define BUSYBOX_CONFIG_GUNZIP 1
#define BUSYBOX_CONFIG_FEATURE_GUNZIP_UNCOMPRESS 1
#define BUSYBOX_CONFIG_GZIP 1
#define BUSYBOX_CONFIG_IPKG 1
#undef BUSYBOX_CONFIG_RPM2CPIO
#undef BUSYBOX_CONFIG_RPM
#define BUSYBOX_CONFIG_TAR 1
#define BUSYBOX_CONFIG_FEATURE_TAR_CREATE 1
#define BUSYBOX_CONFIG_FEATURE_TAR_BZIP2 1
#define BUSYBOX_CONFIG_FEATURE_TAR_FROM 1
#define BUSYBOX_CONFIG_FEATURE_TAR_GZIP 1
#undef BUSYBOX_CONFIG_FEATURE_TAR_COMPRESS
#undef BUSYBOX_CONFIG_FEATURE_TAR_OLDGNU_COMPATABILITY
#define BUSYBOX_CONFIG_FEATURE_TAR_GNU_EXTENSIONS 1
#undef BUSYBOX_CONFIG_FEATURE_TAR_LONG_OPTIONS
#undef BUSYBOX_CONFIG_UNCOMPRESS
#undef BUSYBOX_CONFIG_UNZIP

/*
 * Common options for cpio and tar
 */
#undef BUSYBOX_CONFIG_FEATURE_UNARCHIVE_TAPE

/*
 * Coreutils
 */
#define BUSYBOX_CONFIG_BASENAME 1
#undef BUSYBOX_CONFIG_CAL
#define BUSYBOX_CONFIG_CAT 1
#define BUSYBOX_CONFIG_CHGRP 1
#define BUSYBOX_CONFIG_CHMOD 1
#define BUSYBOX_CONFIG_CHOWN 1
#define BUSYBOX_CONFIG_CHROOT 1
#undef BUSYBOX_CONFIG_CMP
#define BUSYBOX_CONFIG_CP 1
#define BUSYBOX_CONFIG_CUT 1
#define BUSYBOX_CONFIG_DATE 1
#define BUSYBOX_CONFIG_FEATURE_DATE_ISOFMT 1
#define BUSYBOX_CONFIG_DD 1
#define BUSYBOX_CONFIG_DF 1
#define BUSYBOX_CONFIG_DIRNAME 1
#undef BUSYBOX_CONFIG_DOS2UNIX
#define BUSYBOX_CONFIG_DU 1
#define BUSYBOX_CONFIG_FEATURE_DU_DEFALT_BLOCKSIZE_1K 1
#define BUSYBOX_CONFIG_ECHO 1
#define BUSYBOX_CONFIG_FEATURE_FANCY_ECHO 1
#define BUSYBOX_CONFIG_ENV 1
#define BUSYBOX_CONFIG_EXPR 1
#define BUSYBOX_CONFIG_FALSE 1
#undef BUSYBOX_CONFIG_FOLD
#define BUSYBOX_CONFIG_HEAD 1
#define BUSYBOX_CONFIG_FEATURE_FANCY_HEAD 1
#define BUSYBOX_CONFIG_HOSTID 1
#define BUSYBOX_CONFIG_ID 1
#undef BUSYBOX_CONFIG_INSTALL
#define BUSYBOX_CONFIG_LENGTH 1
#define BUSYBOX_CONFIG_LN 1
#undef BUSYBOX_CONFIG_LOGNAME
#define BUSYBOX_CONFIG_LS 1
#define BUSYBOX_CONFIG_FEATURE_LS_FILETYPES 1
#define BUSYBOX_CONFIG_FEATURE_LS_FOLLOWLINKS 1
#define BUSYBOX_CONFIG_FEATURE_LS_RECURSIVE 1
#define BUSYBOX_CONFIG_FEATURE_LS_SORTFILES 1
#define BUSYBOX_CONFIG_FEATURE_LS_TIMESTAMPS 1
#define BUSYBOX_CONFIG_FEATURE_LS_USERNAME 1
#define BUSYBOX_CONFIG_FEATURE_LS_COLOR 1
#define BUSYBOX_CONFIG_MD5SUM 1
#define BUSYBOX_CONFIG_MKDIR 1
#define BUSYBOX_CONFIG_MKFIFO 1
#define BUSYBOX_CONFIG_MKNOD 1
#define BUSYBOX_CONFIG_MV 1
#undef BUSYBOX_CONFIG_OD
#define BUSYBOX_CONFIG_PRINTF 1
#define BUSYBOX_CONFIG_PWD 1
#undef BUSYBOX_CONFIG_REALPATH
#define BUSYBOX_CONFIG_RM 1
#define BUSYBOX_CONFIG_RMDIR 1
#define BUSYBOX_CONFIG_SEQ 1
#undef BUSYBOX_CONFIG_SHA1SUM
#define BUSYBOX_CONFIG_SLEEP 1
#define BUSYBOX_CONFIG_FEATURE_FANCY_SLEEP 1
#define BUSYBOX_CONFIG_SORT 1
#undef BUSYBOX_CONFIG_STTY
#define BUSYBOX_CONFIG_SYNC 1
#define BUSYBOX_CONFIG_TAIL 1
#define BUSYBOX_CONFIG_FEATURE_FANCY_TAIL 1
#define BUSYBOX_CONFIG_TEE 1
#define BUSYBOX_CONFIG_FEATURE_TEE_USE_BLOCK_IO 1
#define BUSYBOX_CONFIG_TEST 1

/*
 * test (forced enabled for use with shell)
 */
#undef BUSYBOX_CONFIG_FEATURE_TEST_64
#define BUSYBOX_CONFIG_TOUCH 1
#define BUSYBOX_CONFIG_TR 1
#define BUSYBOX_CONFIG_TRUE 1
#undef BUSYBOX_CONFIG_TTY
#define BUSYBOX_CONFIG_UNAME 1
#define BUSYBOX_CONFIG_UNIQ 1
#undef BUSYBOX_CONFIG_USLEEP
#undef BUSYBOX_CONFIG_UUDECODE
#undef BUSYBOX_CONFIG_UUENCODE
#undef BUSYBOX_CONFIG_WATCH
#define BUSYBOX_CONFIG_WC 1
#undef BUSYBOX_CONFIG_WHO
#undef BUSYBOX_CONFIG_WHOAMI
#define BUSYBOX_CONFIG_YES 1

/*
 * Common options for cp and mv
 */
#define BUSYBOX_CONFIG_FEATURE_PRESERVE_HARDLINKS 1

/*
 * Common options for ls and more
 */
#define BUSYBOX_CONFIG_FEATURE_AUTOWIDTH 1

/*
 * Common options for df, du, ls
 */
#define BUSYBOX_CONFIG_FEATURE_HUMAN_READABLE 1

/*
 * Common options for md5sum, sha1sum
 */
#define BUSYBOX_CONFIG_FEATURE_MD5_SHA1_SUM_CHECK 1

/*
 * Console Utilities
 */
#undef BUSYBOX_CONFIG_CHVT
#define BUSYBOX_CONFIG_CLEAR 1
#undef BUSYBOX_CONFIG_DEALLOCVT
#undef BUSYBOX_CONFIG_DUMPKMAP
#undef BUSYBOX_CONFIG_LOADFONT
#undef BUSYBOX_CONFIG_LOADKMAP
#undef BUSYBOX_CONFIG_OPENVT
#define BUSYBOX_CONFIG_RESET 1
#undef BUSYBOX_CONFIG_SETKEYCODES

/*
 * Debian Utilities
 */
#define BUSYBOX_CONFIG_MKTEMP 1
#undef BUSYBOX_CONFIG_PIPE_PROGRESS
#undef BUSYBOX_CONFIG_READLINK
#define BUSYBOX_CONFIG_RUN_PARTS 1
#define BUSYBOX_CONFIG_START_STOP_DAEMON 1
#define BUSYBOX_CONFIG_WHICH 1

/*
 * Editors
 */
#define BUSYBOX_CONFIG_AWK 1
#define BUSYBOX_CONFIG_FEATURE_AWK_MATH 1
#undef BUSYBOX_CONFIG_PATCH
#define BUSYBOX_CONFIG_SED 1
#define BUSYBOX_CONFIG_VI 1
#define BUSYBOX_CONFIG_FEATURE_VI_COLON 1
#define BUSYBOX_CONFIG_FEATURE_VI_YANKMARK 1
#define BUSYBOX_CONFIG_FEATURE_VI_SEARCH 1
#define BUSYBOX_CONFIG_FEATURE_VI_USE_SIGNALS 1
#define BUSYBOX_CONFIG_FEATURE_VI_DOT_CMD 1
#define BUSYBOX_CONFIG_FEATURE_VI_READONLY 1
#define BUSYBOX_CONFIG_FEATURE_VI_SETOPTS 1
#define BUSYBOX_CONFIG_FEATURE_VI_SET 1
#define BUSYBOX_CONFIG_FEATURE_VI_WIN_RESIZE 1
#define BUSYBOX_CONFIG_FEATURE_VI_OPTIMIZE_CURSOR 1

/*
 * Finding Utilities
 */
#define BUSYBOX_CONFIG_FIND 1
#undef BUSYBOX_CONFIG_FEATURE_FIND_MTIME
#define BUSYBOX_CONFIG_FEATURE_FIND_PERM 1
#define BUSYBOX_CONFIG_FEATURE_FIND_TYPE 1
#define BUSYBOX_CONFIG_FEATURE_FIND_XDEV 1
#undef BUSYBOX_CONFIG_FEATURE_FIND_NEWER
#undef BUSYBOX_CONFIG_FEATURE_FIND_INUM
#define BUSYBOX_CONFIG_GREP 1
#define BUSYBOX_CONFIG_FEATURE_GREP_EGREP_ALIAS 1
#define BUSYBOX_CONFIG_FEATURE_GREP_FGREP_ALIAS 1
#define BUSYBOX_CONFIG_FEATURE_GREP_CONTEXT 1
#define BUSYBOX_CONFIG_XARGS 1
#define BUSYBOX_CONFIG_FEATURE_XARGS_SUPPORT_CONFIRMATION 1
#define BUSYBOX_CONFIG_FEATURE_XARGS_SUPPORT_QUOTES 1
#define BUSYBOX_CONFIG_FEATURE_XARGS_SUPPORT_TERMOPT 1
#define BUSYBOX_CONFIG_FEATURE_XARGS_SUPPORT_ZERO_TERM 1

/*
 * Init Utilities
 */
#define BUSYBOX_CONFIG_INIT 1
#define BUSYBOX_CONFIG_FEATURE_USE_INITTAB 1
#define BUSYBOX_CONFIG_FEATURE_INITRD 1
#undef BUSYBOX_CONFIG_FEATURE_INIT_COREDUMPS
#undef BUSYBOX_CONFIG_FEATURE_EXTRA_QUIET
#undef BUSYBOX_CONFIG_HALT
#undef BUSYBOX_CONFIG_POWEROFF
#define BUSYBOX_CONFIG_REBOOT 1
#undef BUSYBOX_CONFIG_MESG

/*
 * Login/Password Management Utilities
 */
#undef BUSYBOX_CONFIG_USE_BB_PWD_GRP
#undef BUSYBOX_CONFIG_ADDGROUP
#undef BUSYBOX_CONFIG_DELGROUP
#undef BUSYBOX_CONFIG_ADDUSER
#undef BUSYBOX_CONFIG_DELUSER
#define BUSYBOX_CONFIG_GETTY 1
#undef BUSYBOX_CONFIG_FEATURE_U_W_TMP
#define BUSYBOX_CONFIG_LOGIN 1
#undef BUSYBOX_CONFIG_FEATURE_SECURETTY
#define BUSYBOX_CONFIG_PASSWD 1
#undef BUSYBOX_CONFIG_SU
#undef BUSYBOX_CONFIG_SULOGIN
#undef BUSYBOX_CONFIG_VLOCK

/*
 * Common options for adduser, deluser, login, su
 */
#undef BUSYBOX_CONFIG_FEATURE_SHADOWPASSWDS

/*
 * Miscellaneous Utilities
 */
#undef BUSYBOX_CONFIG_ADJTIMEX
#define BUSYBOX_CONFIG_CROND 1
#undef BUSYBOX_CONFIG_FEATURE_CROND_CALL_SENDMAIL
#define BUSYBOX_CONFIG_CRONTAB 1
#undef BUSYBOX_CONFIG_DC
#undef BUSYBOX_CONFIG_DEVFSD
#undef BUSYBOX_CONFIG_LAST
#undef BUSYBOX_CONFIG_HDPARM
#undef BUSYBOX_CONFIG_MAKEDEVS
#undef BUSYBOX_CONFIG_MT
#undef BUSYBOX_CONFIG_RX
#define BUSYBOX_CONFIG_STRINGS 1
#define BUSYBOX_CONFIG_TIME 1
#define BUSYBOX_CONFIG_WATCHDOG 1

/*
 * Linux Module Utilities
 */
#define BUSYBOX_CONFIG_INSMOD 1
#define BUSYBOX_CONFIG_FEATURE_2_4_MODULES 1
#define BUSYBOX_CONFIG_FEATURE_2_6_MODULES 1
#undef BUSYBOX_CONFIG_FEATURE_INSMOD_VERSION_CHECKING
#undef BUSYBOX_CONFIG_FEATURE_INSMOD_KSYMOOPS_SYMBOLS
#undef BUSYBOX_CONFIG_FEATURE_INSMOD_LOADINKMEM
#undef BUSYBOX_CONFIG_FEATURE_INSMOD_LOAD_MAP
#define BUSYBOX_CONFIG_LSMOD 1
#define BUSYBOX_CONFIG_FEATURE_QUERY_MODULE_INTERFACE 1
#undef BUSYBOX_CONFIG_MODPROBE
#define BUSYBOX_CONFIG_RMMOD 1
#define BUSYBOX_CONFIG_FEATURE_CHECK_TAINTED_MODULE 1

/*
 * Networking Utilities
 */
#define BUSYBOX_CONFIG_FEATURE_IPV6 1
#define BUSYBOX_CONFIG_ARPING 1
#undef BUSYBOX_CONFIG_FTPGET
#undef BUSYBOX_CONFIG_FTPPUT
#define BUSYBOX_CONFIG_HOSTNAME 1
#define BUSYBOX_CONFIG_HTTPD 1
#undef BUSYBOX_CONFIG_FEATURE_HTTPD_USAGE_FROM_INETD_ONLY
#define BUSYBOX_CONFIG_FEATURE_HTTPD_BASIC_AUTH 1
#define BUSYBOX_CONFIG_FEATURE_HTTPD_AUTH_MD5 1
#define BUSYBOX_CONFIG_FEATURE_HTTPD_RELOAD_CONFIG_SIGHUP 1
#undef BUSYBOX_CONFIG_FEATURE_HTTPD_SETUID
#define BUSYBOX_CONFIG_FEATURE_HTTPD_CONFIG_WITH_MIME_TYPES 1
#define BUSYBOX_CONFIG_FEATURE_HTTPD_CGI 1
#define BUSYBOX_CONFIG_FEATURE_HTTPD_SET_REMOTE_PORT_TO_ENV 1
#define BUSYBOX_CONFIG_FEATURE_HTTPD_ENCODE_URL_STR 1
#define BUSYBOX_CONFIG_IFCONFIG 1
#define BUSYBOX_CONFIG_FEATURE_IFCONFIG_STATUS 1
#undef BUSYBOX_CONFIG_FEATURE_IFCONFIG_SLIP
#undef BUSYBOX_CONFIG_FEATURE_IFCONFIG_MEMSTART_IOADDR_IRQ
#define BUSYBOX_CONFIG_FEATURE_IFCONFIG_HW 1
#define BUSYBOX_CONFIG_FEATURE_IFCONFIG_BROADCAST_PLUS 1
#define BUSYBOX_CONFIG_IFUPDOWN 1
#undef BUSYBOX_CONFIG_FEATURE_IFUPDOWN_IP
#undef BUSYBOX_CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN
#define BUSYBOX_CONFIG_FEATURE_IFUPDOWN_IPV4 1
#undef BUSYBOX_CONFIG_FEATURE_IFUPDOWN_IPV6
#undef BUSYBOX_CONFIG_FEATURE_IFUPDOWN_IPX
#undef BUSYBOX_CONFIG_FEATURE_IFUPDOWN_MAPPING
#undef BUSYBOX_CONFIG_INETD
#undef BUSYBOX_CONFIG_IP
#define BUSYBOX_CONFIG_IPCALC 1
#define BUSYBOX_CONFIG_FEATURE_IPCALC_FANCY 1
#undef BUSYBOX_CONFIG_IPADDR
#undef BUSYBOX_CONFIG_IPLINK
#undef BUSYBOX_CONFIG_IPROUTE
#undef BUSYBOX_CONFIG_IPTUNNEL
#undef BUSYBOX_CONFIG_NAMEIF
#define BUSYBOX_CONFIG_NC 1
#define BUSYBOX_CONFIG_NETMSG 1
#define BUSYBOX_CONFIG_NETSTAT 1
#define BUSYBOX_CONFIG_NSLOOKUP 1
#define BUSYBOX_CONFIG_PING 1
#define BUSYBOX_CONFIG_FEATURE_FANCY_PING 1
#define BUSYBOX_CONFIG_PING6 1
#define BUSYBOX_CONFIG_FEATURE_FANCY_PING6 1
#define BUSYBOX_CONFIG_ROUTE 1
#define BUSYBOX_CONFIG_TELNET 1
#define BUSYBOX_CONFIG_FEATURE_TELNET_TTYPE 1
#undef BUSYBOX_CONFIG_FEATURE_TELNET_AUTOLOGIN
#define BUSYBOX_CONFIG_TELNETD 1
#undef BUSYBOX_CONFIG_FEATURE_TELNETD_INETD
#define BUSYBOX_CONFIG_TFTP 1
#undef BUSYBOX_CONFIG_FEATURE_TFTP_GET
#undef BUSYBOX_CONFIG_FEATURE_TFTP_PUT
#undef BUSYBOX_CONFIG_FEATURE_TFTP_BLOCKSIZE
#undef BUSYBOX_CONFIG_FEATURE_TFTP_DEBUG
#define BUSYBOX_CONFIG_TRACEROUTE 1
#define BUSYBOX_CONFIG_FEATURE_TRACEROUTE_VERBOSE 1
#define BUSYBOX_CONFIG_VCONFIG 1
#define BUSYBOX_CONFIG_WGET 1
#define BUSYBOX_CONFIG_FEATURE_WGET_STATUSBAR 1
#define BUSYBOX_CONFIG_FEATURE_WGET_AUTHENTICATION 1
#define BUSYBOX_CONFIG_FEATURE_WGET_IP6_LITERAL 1

/*
 * udhcp Server/Client
 */
#define BUSYBOX_CONFIG_UDHCPD 1
#define BUSYBOX_CONFIG_UDHCPC 1
#undef BUSYBOX_CONFIG_DUMPLEASES
#undef BUSYBOX_CONFIG_FEATURE_UDHCP_SYSLOG
#undef BUSYBOX_CONFIG_FEATURE_UDHCP_DEBUG

/*
 * Process Utilities
 */
#define BUSYBOX_CONFIG_FREE 1
#define BUSYBOX_CONFIG_KILL 1
#define BUSYBOX_CONFIG_KILLALL 1
#define BUSYBOX_CONFIG_KILLALL5 1
#define BUSYBOX_CONFIG_PIDOF 1
#define BUSYBOX_CONFIG_PS 1
#undef BUSYBOX_CONFIG_RENICE
#define BUSYBOX_CONFIG_TOP 1
#define BUSYBOX_FEATURE_CPU_USAGE_PERCENTAGE 1
#define BUSYBOX_CONFIG_UPTIME 1
#define BUSYBOX_CONFIG_BB_SYSCTL 1

/*
 * Another Bourne-like Shell
 */
#define BUSYBOX_CONFIG_FEATURE_SH_IS_ASH 1
#undef BUSYBOX_CONFIG_FEATURE_SH_IS_HUSH
#undef BUSYBOX_CONFIG_FEATURE_SH_IS_LASH
#undef BUSYBOX_CONFIG_FEATURE_SH_IS_MSH
#undef BUSYBOX_CONFIG_FEATURE_SH_IS_NONE
#define BUSYBOX_CONFIG_ASH 1

/*
 * Ash Shell Options
 */
#define BUSYBOX_CONFIG_ASH_JOB_CONTROL 1
#define BUSYBOX_CONFIG_ASH_ALIAS 1
#define BUSYBOX_CONFIG_ASH_MATH_SUPPORT 1
#undef BUSYBOX_CONFIG_ASH_MATH_SUPPORT_64
#define BUSYBOX_CONFIG_ASH_GETOPTS 1
#define BUSYBOX_CONFIG_ASH_CMDCMD 1
#undef BUSYBOX_CONFIG_ASH_MAIL
#define BUSYBOX_CONFIG_ASH_OPTIMIZE_FOR_SIZE 1
#undef BUSYBOX_CONFIG_ASH_RANDOM_SUPPORT
#undef BUSYBOX_CONFIG_HUSH
#undef BUSYBOX_CONFIG_LASH
#undef BUSYBOX_CONFIG_MSH

/*
 * Bourne Shell Options
 */
#undef BUSYBOX_CONFIG_FEATURE_SH_EXTRA_QUIET
#undef BUSYBOX_CONFIG_FEATURE_SH_STANDALONE_SHELL
#define BUSYBOX_CONFIG_FEATURE_COMMAND_EDITING 1
#define BUSYBOX_CONFIG_FEATURE_COMMAND_HISTORY 15
#undef BUSYBOX_CONFIG_FEATURE_COMMAND_SAVEHISTORY
#define BUSYBOX_CONFIG_FEATURE_COMMAND_TAB_COMPLETION 1
#undef BUSYBOX_CONFIG_FEATURE_COMMAND_USERNAME_COMPLETION
#define BUSYBOX_CONFIG_FEATURE_SH_FANCY_PROMPT 1

/*
 * System Logging Utilities
 */
#define BUSYBOX_CONFIG_SYSLOGD 1
#define BUSYBOX_CONFIG_FEATURE_ROTATE_LOGFILE 1
#define BUSYBOX_CONFIG_FEATURE_REMOTE_LOG 1
#define BUSYBOX_CONFIG_FEATURE_IPC_SYSLOG 1
#define BUSYBOX_CONFIG_FEATURE_IPC_SYSLOG_BUFFER_SIZE 16
#define BUSYBOX_CONFIG_LOGREAD 1
#undef BUSYBOX_CONFIG_FEATURE_LOGREAD_REDUCED_LOCKING
#define BUSYBOX_CONFIG_KLOGD 1
#define BUSYBOX_CONFIG_LOGGER 1

/*
 * Linux System Utilities
 */
#define BUSYBOX_CONFIG_DMESG 1
#undef BUSYBOX_CONFIG_FBSET
#undef BUSYBOX_CONFIG_FDFLUSH
#undef BUSYBOX_CONFIG_FDFORMAT
#undef BUSYBOX_CONFIG_FDISK
#define BUSYBOX_FDISK_SUPPORT_LARGE_DISKS 1
#undef BUSYBOX_CONFIG_FREERAMDISK
#undef BUSYBOX_CONFIG_FSCK_MINIX
#undef BUSYBOX_CONFIG_MKFS_MINIX
#undef BUSYBOX_CONFIG_GETOPT
#define BUSYBOX_CONFIG_HEXDUMP 1
#undef BUSYBOX_CONFIG_HWCLOCK
#undef BUSYBOX_CONFIG_LOSETUP
#undef BUSYBOX_CONFIG_MKSWAP
#define BUSYBOX_CONFIG_MORE 1
#define BUSYBOX_CONFIG_FEATURE_USE_TERMIOS 1
#define BUSYBOX_CONFIG_PIVOT_ROOT 1
#define BUSYBOX_CONFIG_RDATE 1
#undef BUSYBOX_CONFIG_SWAPONOFF
#define BUSYBOX_CONFIG_MOUNT 1
#define BUSYBOX_CONFIG_NFSMOUNT 1
#define BUSYBOX_CONFIG_UMOUNT 1
#define BUSYBOX_CONFIG_FEATURE_MOUNT_FORCE 1

/*
 * Common options for mount/umount
 */
#define BUSYBOX_CONFIG_FEATURE_MOUNT_LOOP 1
#undef BUSYBOX_CONFIG_FEATURE_MTAB_SUPPORT

/*
 * Debugging Options
 */
#undef BUSYBOX_CONFIG_DEBUG
#define BR2_PACKAGE_DNSMASQ 1
#undef BR2_PACKAGE_IPKG

/*
 * iptables.......................... IPv4 / IPv6 firewall administration
 */
#define BR2_COMPILE_IPTABLES 1
#define BR2_PACKAGE_IPTABLES 1
#undef BR2_PACKAGE_MTD
#undef BR2_PACKAGE_MTD_STATIC

/*
 * Applications
 */

/*
 * collectd.......................... Lightweight system statistics collection daemon
 */
#undef BR2_PACKAGE_COLLECTD
#undef BR2_PACKAGE_GPSD
#define BR2_PACKAGE_HASERL 1
#undef BR2_PACKAGE_IRSSI
#undef BR2_PACKAGE_LCD4LINUX
#undef BR2_PACKAGE_LESS

/*
 * lua............................... LUA programming language
 */
#undef BR2_PACKAGE_LIBLUA
#undef BR2_PACKAGE_LUA
#undef BR2_PACKAGE_LUAC
#undef BR2_PACKAGE_LUA_EXAMPLES
#undef BR2_PACKAGE_MICROPERL
#undef BR2_PACKAGE_MONIT
#undef BR2_PACKAGE_MONIT_NOSSL
#undef BR2_PACKAGE_OSIRISD

/*
 * php4.............................. PHP4 Hypertext preprocessor
 */

/*
 * Server API ---
 */
#undef BR2_PACKAGE_PHP4_CLI
#undef BR2_PACKAGE_PHP4_CGI
#undef BR2_PACKAGE_PHP4_FASTCGI

/*
 * Extensions ---
 */

/*
 * php5.............................. PHP5 Hypertext preprocessor
 */

/*
 * Server API ---
 */
#undef BR2_PACKAGE_PHP5_CLI
#undef BR2_PACKAGE_PHP5_CGI
#undef BR2_PACKAGE_PHP5_FASTCGI

/*
 * Extensions ---
 */
#undef BR2_PACKAGE_PSYBNC

/*
 * sablevm........................... A Java Virtual Machine (JVM) implementation
 */
#undef BR2_PACKAGE_SABLEVM
#undef BR2_PACKAGE_LIBSABLEVM_CLASSPATH
#undef BR2_PACKAGE_LIBFFI_SABLE
#undef BR2_PACKAGE_SANE_BACKENDS

/*
 * rrdtool........................... Round-Robin Database (RRD) libraries and tools
 */
#undef BR2_COMPILE_RRDTOOL
#undef BR2_COMPILE_RRDTOOL1
#undef BR2_PACKAGE_SCREEN

/*
 * Networking
 */
#undef BR2_PACKAGE_AIRCRACK
#undef BR2_PACKAGE_AMWALL
#undef BR2_PACKAGE_ARPD
#undef BR2_PACKAGE_ARPTABLES
#undef BR2_PACKAGE_ARPWATCH

/*
 * asterisk.......................... Complete open source PBX
 */
#undef BR2_PACKAGE_ASTERISK
#undef BR2_PACKAGE_ASTERISK_MINI
#undef BR2_PACKAGE_ATFTP
#undef BR2_PACKAGE_ATFTPD

/*
 * avahi............................. An mDNS/DNS-SD (aka RendezVous/Bonjour/ZeroConf) implementation
 */
#undef BR2_PACKAGE_AVAHI_DAEMON
#undef BR2_PACKAGE_LIBAVAHI

/*
 * bind.............................. A DNS server implementation
 */
#undef BR2_PACKAGE_BIND_CLIENT
#undef BR2_PACKAGE_BIND_SERVER
#undef BR2_PACKAGE_BWM
#undef BR2_PACKAGE_CHILLISPOT
#undef BR2_PACKAGE_CIFSMOUNT
#undef BR2_PACKAGE_CUPS
#undef BR2_PACKAGE_CUTTER
#undef BR2_PACKAGE_DHCP_RELAY
#undef BR2_PACKAGE_DHCP_SERVER
#undef BR2_PACKAGE_DHCP_FORWARDER
#define BR2_PACKAGE_DROPBEAR 1
#undef BR2_PACKAGE_DSNIFF
#undef BR2_PACKAGE_ETHER_WAKE
#undef BR2_PACKAGE_EZIPUPDATE
#undef BR2_PACKAGE_FPING
#undef BR2_PACKAGE_FPROBE_ULOG

/*
 * freeradius........................ A Flexible RADIUS server implementation
 */
#undef BR2_PACKAGE_FREERADIUS

/*
 * howl.............................. A Zeroconf networking implementation
 */
#undef BR2_PACKAGE_LIBHOWL

/*
 * Daemons ---
 */
#undef BR2_PACKAGE_AUTOIPD
#undef BR2_PACKAGE_MDNSRESPONDER
#undef BR2_PACKAGE_NIFD
#undef BR2_PACKAGE_HOSTAP_UTILS
#undef BR2_PACKAGE_HOSTAPD
#undef BR2_PACKAGE_HTPDATE

/*
 * httping........................... Httping is like 'ping' but for http-requests.
 */
#define BR2_PACKAGE_HTTPING_WITH_SSL 1

/*
 * iproute2.......................... A collection of utilites for controlling TCP/IP networking and Traffic Control
 */
#define BR2_COMPILE_IPROUTE2 1
#define BR2_PACKAGE_IP 1
#define BR2_PACKAGE_TC 1
#undef BR2_PACKAGE_IPSEC_TOOLS
#undef BR2_PACKAGE_IPSET
#undef BR2_PACKAGE_IPTABLES_SNMP
#undef BR2_PACKAGE_IPTRAF
#undef BR2_PACKAGE_KISMET_CLIENT
#undef BR2_PACKAGE_KISMET_DRONE
#undef BR2_PACKAGE_KISMET_SERVER
#undef BR2_PACKAGE_KNOCK
#undef BR2_PACKAGE_KNOCKD
#undef BR2_PACKAGE_L2TPD
#undef BR2_PACKAGE_L2TPNS

/*
 * lighttpd.......................... Flexible and lightweight web server
 */
#undef BR2_PACKAGE_LINUX_ATM
#undef BR2_PACKAGE_MACCHANGER

/*
 * mini-httpd........................ A small web server
 */
#define BR2_COMPILE_MINI_HTTPD 1
#define BR2_PACKAGE_MINI_HTTPD 1
#undef BR2_PACKAGE_MINI_HTTPD_MATRIXSSL
#undef BR2_PACKAGE_MINI_HTTPD_OPENSSL
#undef BR2_PACKAGE_MINI_SENDMAIL

/*
 * net-snmp.......................... Open source SNMP (Simple Network Management Protocol) implementation
 */
#undef BR2_PACKAGE_LIBNETSNMP
#undef BR2_PACKAGE_SNMPD
#undef BR2_PACKAGE_SNMPD_STATIC
#undef BR2_PACKAGE_NETSTAT_NAT
#undef BR2_PACKAGE_NFS_SERVER
#undef BR2_PACKAGE_NOCATSPLASH

/*
 * olsrd............................. OLSR (Optimized Link State Routing) daemon
 */
#undef BR2_PACKAGE_OLSRD

/*
 * openssh........................... A free implementation of the Secure Shell protocol
 */
#undef BR2_PACKAGE_OPENSSH_CLIENT
#undef BR2_PACKAGE_OPENSSH_SERVER
#undef BR2_PACKAGE_OPENSSH_SFTP_CLIENT
#undef BR2_PACKAGE_OPENSSH_SFTP_SERVER
#undef BR2_PACKAGE_OPENSWAN

/*
 * openvpn........................... Open source VPN solution using SSL
 */
#define BR2_COMPILE_OPENVPN_WITH_SERVER 1
#define BR2_COMPILE_OPENVPN_WITH_HTTP 1
#undef BR2_COMPILE_OPENVPN_WITH_OPENSSL
#define BR2_COMPILE_OPENVPN_WITH_LZO 1
#define BR2_COMPILE_OPENVPN_WITH_PASSWORD_SAVE 1
#undef BR2_COMPILE_OPENVPN_WITH_SMALL
#undef BR2_PACKAGE_PARPROUTED
#undef BR2_PACKAGE_PIPACS

/*
 * pmacct............................ IPv4/IPv6 accounting and aggregation tools
 */
#undef BR2_PACKAGE_NFACCTD_BASIC
#undef BR2_PACKAGE_NFACCTD_MYSQL
#undef BR2_PACKAGE_NFACCTD_PGSQL
#undef BR2_PACKAGE_NFACCTD_SQLITE
#undef BR2_PACKAGE_NFACCTD_CUSTOM
#undef BR2_PACKAGE_PMACCTD_BASIC
#undef BR2_PACKAGE_PMACCTD_MYSQL
#undef BR2_PACKAGE_PMACCTD_PGSQL
#undef BR2_PACKAGE_PMACCTD_SQLITE
#undef BR2_PACKAGE_PMACCTD_CUSTOM
#undef BR2_PACKAGE_PMACCT_CLIENT
#undef BR2_PACKAGE_PORTMAP
#undef BR2_PACKAGE_PORTSENTRY

/*
 * ppp............................... PPP (Point-to-Point Protocol) daemon
 */
#define BR2_PACKAGE_PPP_WITH_FILTER 1
#undef BR2_PACKAGE_PPP_MOD_PPPOA
#undef BR2_PACKAGE_PTUNNEL

/*
 * quagga............................ The Quagga Software Routing Suite
 */
#undef BR2_PACKAGE_QUAGGA
#undef BR2_PACKAGE_RADDUMP
#undef BR2_PACKAGE_RARPD
#undef BR2_PACKAGE_REAIM
#undef BR2_PACKAGE_ROBOCFG
#undef BR2_PACKAGE_PPPOE_RELAY
#undef BR2_PACKAGE_PPPOE_SERVER
#undef BR2_PACKAGE_PPPOE_SNIFF
#undef BR2_PACKAGE_RRS
#undef BR2_PACKAGE_RSYNC
#undef BR2_PACKAGE_SAMBA
#undef BR2_PACKAGE_SAMBA_CLIENT
#undef BR2_PACKAGE_SCDP
#undef BR2_PACKAGE_SHAT
#undef BR2_PACKAGE_SIPROXD
#undef BR2_PACKAGE_SIPSAK
#undef BR2_PACKAGE_SLURM

/*
 * snort............................. Ligthweight Network Intrusion Detection System (NIDS)
 */
#undef BR2_PACKAGE_SNORT_BASIC
#undef BR2_PACKAGE_SNORT_MYSQL
#undef BR2_PACKAGE_SNORT_PGSQL
#undef BR2_PACKAGE_SNORT_CUSTOM

/*
 * snort-wireless.................... Ligthweight Wireless Network Intrusion Detection System (NIDS)
 */
#undef BR2_PACKAGE_SNORT_WIRELESS_BASIC
#undef BR2_PACKAGE_SNORT_WIRELESS_MYSQL
#undef BR2_PACKAGE_SNORT_WIRELESS_PGSQL
#undef BR2_PACKAGE_SNORT_WIRELESS_CUSTOM
#undef BR2_PACKAGE_SOCAT
#undef BR2_PACKAGE_SSLTUNNEL
#undef BR2_PACKAGE_SRELAY
#undef BR2_PACKAGE_TMSNC
#undef BR2_PACKAGE_TINC

/*
 * tinyproxy......................... Tinyproxy is a lightweight HTTP and HTTPS proxy.
 */
#define BR2_COMPILE_TINYPROXY_WITH_TRANSPARENT_PROXY 1
#define BR2_COMPILE_TINYPROXY_WITH_FILTER 1
#define BR2_COMPILE_TINYPROXY_WITH_UPSTREAM 1
#undef BR2_PACKAGE_TOR

/*
 * ulogd............................. Netfilter userspace logging daemon
 */
#undef BR2_PACKAGE_ULOGD

/*
 * updatedd.......................... A tool to update dynamic dns services
 */
#undef BR2_PACKAGE_UPDATEDD
#undef BR2_PACKAGE_VGP
#undef BR2_PACKAGE_VNC_REFLECTOR
#undef BR2_PACKAGE_VNSTAT
#undef BR2_PACKAGE_VPNC
#undef BR2_PACKAGE_VRRPD
#undef BR2_PACKAGE_VSFTPD
#undef BR2_PACKAGE_VTUN
#undef BR2_PACKAGE_WCCPD
#undef BR2_PACKAGE_WIFIDOG
#undef BR2_PACKAGE_WIRELESS_TOOLS
#undef BR2_PACKAGE_WIVIZ
#undef BR2_PACKAGE_WKNOCK
#undef BR2_PACKAGE_WOL
#undef BR2_PACKAGE_WONDERSHAPER
#undef BR2_PACKAGE_WPA_SUPPLICANT
#undef BR2_PACKAGE_WPUT
#undef BR2_PACKAGE_WX200D
#undef BR2_PACKAGE_XINETD
#undef BR2_PACKAGE_XSUPPLICANT

/*
 * IPv6
 */
#undef BR2_PACKAGE_6TUNNEL
#undef BR2_PACKAGE_AICCU
#undef BR2_PACKAGE_DHCP6
#undef BR2_PACKAGE_MIREDO
#undef BR2_PACKAGE_MIREDO_SERVER
#undef BR2_PACKAGE_MRD6

/*
 * ndisc6............................ IPv6 discovery tools
 */
#undef BR2_PACKAGE_NDISC6
#undef BR2_PACKAGE_RDISC6
#undef BR2_PACKAGE_TCPTRACEROUTE6
#undef BR2_PACKAGE_RADVD

/*
 * Libraries
 */
#undef BR2_PACKAGE_CGILIB
#undef BR2_PACKAGE_GLIB1
#undef BR2_PACKAGE_ID3LIB
#undef BR2_PACKAGE_LIBAMSEL
#undef BR2_PACKAGE_LIBAO
#undef BR2_PACKAGE_LIBART
#undef BR2_PACKAGE_LIBCLI
#undef BR2_PACKAGE_CLINKC
#undef BR2_PACKAGE_LIBCURL
#undef BR2_PACKAGE_LIBDAEMON
#undef BR2_PACKAGE_LIBDB
#undef BR2_PACKAGE_LIBDNET
#undef BR2_PACKAGE_LIBELF
#undef BR2_PACKAGE_LIBEVENT
#undef BR2_PACKAGE_LIBEXPAT
#undef BR2_PACKAGE_LIBFLAC
#undef BR2_PACKAGE_LIBFREETYPE
#undef BR2_PACKAGE_LIBGCRYPT
#undef BR2_PACKAGE_LIBGD
#undef BR2_PACKAGE_LIBGMP
#undef BR2_PACKAGE_LIBGNUTLS
#undef BR2_PACKAGE_LIBGPG_ERROR
#undef BR2_PACKAGE_LIBGSM
#undef BR2_PACKAGE_LIBID3TAG
#undef BR2_PACKAGE_LIBJPEG
#undef BR2_PACKAGE_LIBLTDL
#undef BR2_PACKAGE_LIBMAD
#undef BR2_PACKAGE_LIBMYSQLCLIENT
#undef BR2_PACKAGE_LIBOGG
#undef BR2_PACKAGE_LIBOPENCDK
#undef BR2_PACKAGE_LIBOPENLDAP
#undef BR2_PACKAGE_LIBOSIP2
#undef BR2_PACKAGE_LIBSASL2
#undef BR2_PACKAGE_LIBSPEEX
#undef BR2_PACKAGE_LIBTASN1
#undef BR2_PACKAGE_LIBVORBIS
#undef BR2_PACKAGE_LIBVORBISIDEC
#undef BR2_PACKAGE_LIBXML2
#undef BR2_PACKAGE_LIBXSLT
#define BR2_PACKAGE_ZLIB 1

/*
 * Multimedia
 */
#undef BR2_PACKAGE_GMEDIASERVER
#undef BR2_PACKAGE_ICECAST
#undef BR2_PACKAGE_MADPLAY

/*
 * mpd............................... Music Player Daemon
 */
#undef BR2_PACKAGE_MPD
#undef BR2_PACKAGE_MT_DAAPD
#undef BR2_PACKAGE_PALANTIR
#undef BR2_PACKAGE_PEERCAST
#undef BR2_PACKAGE_SETPWC

/*
 * Serial communications & terminal emulation
 */
#undef BR2_PACKAGE_HEYU
#undef BR2_PACKAGE_LRZSZ
#undef BR2_PACKAGE_MICROCOM
#undef BR2_PACKAGE_SERDISPLIB

/*
 * Utilities
 */
#undef BR2_PACKAGE_BC
#undef BR2_PACKAGE_DC
#undef BR2_PACKAGE_GDBSERVER
#undef BR2_PACKAGE_UDEV

/*
 * FileSystems related
 */
#undef BR2_PACKAGE_LIBFUSE

/*
 * util-linux
 */
#undef BR2_PACKAGE_LOSETUP
#undef BR2_PACKAGE_SWAP_UTILS

/*
 * Bluetooth
 */
#undef BR2_PACKAGE_BLUEZ_LIBS
#undef BR2_PACKAGE_BLUEZ_UTILS
#undef BR2_PACKAGE_MIAX

/*
 * Extra stuff
 */

/*
 * webface........................... SigrandWebface
 */
#define BR2_PACKAGE_WEBFACE 1
#undef BR2_PACKAGE_SDK
#undef BR2_PACKAGE_IMAGEBUILDER

/*
 * Runtime Configuration
 */
#define BR2_SYSCONF_TELNET_FAILSAFE_ONLY 1
#undef BR2_SYSCONF_TELNET_OPEN

/*
 * Failsafe configuration
 */
#define BR2_SYSCONF_FAILSAFE_IP "192.168.1.1"
#define BR2_SYSCONF_FAILSAFE_NETMASK "255.255.255.0"
#define BR2_SYSCONF_FAILSAFE_MAC "00:00:BA:DC:0D:ED"

/*
 * Target Root Filesystem
 */
#undef BR2_TARGET_ROOTFS_JFFS2
#define BR2_TARGET_ROOTFS_SQUASHFS_LZMA 1
#undef BR2_TARGET_ROOTFS_TGZ

/*
 * Kernel Configuration / Device Support
 */

/*
 * Device specific configuration
 */
#undef MIDGE_TYPE_JFFS2
#define MIDGE_TYPE_TMPFS 1
#undef MIDGE_TYPE_USB
#define MIDGE_KERNEL_BLOCKS 10
#define MIDGE_SQUASHFS_BLOCKS 16
#define BR2_PACKAGE_KMOD_ADM5120_SW 1

/*
 * Kernel modules
 */

/*
 * Networking modules
 */
#define BR2_PACKAGE_KMOD_SCHED 1

/*
 * Filtering/Firewalling
 */
#define BR2_PACKAGE_KMOD_IPTABLES 1

/*
 * Block devices support
 */

/*
 * Filesystems support
 */

/*
 * Multimedia devices support
 */
#undef BR2_PACKAGE_KMOD_PWC
#undef BR2_PACKAGE_KMOD_VIDEODEV

/*
 * Native Language support
 */

/*
 * USB support
 */

/*
 * Misc. devices support
 */

/*
 * Additional kernel modules
 */
#undef BR2_PACKAGE_KMOD_MADWIFI
#undef BR2_PACKAGE_KMOD_SPCA5XX
