#!/bin/sh

pn=$0
usage()
{
  echo 1>&2 "Usage $pn {sigrand | zelax | sviazinvest} [-nofw]"
  exit 1
}

if test "$#" -lt 1 -o "$#" -gt 2; then
  usage
fi

oem=$1; shift
case $oem in
     sigrand) ;;
       zelax) ;;
 sviazinvest) ;;
           *) usage;;
esac

unset nofw
if test "$#" -eq 1; then
   case $1 in
	-nofw)	nofw=$1;
		export SIGRAND_LINUX_NOFW=1; # target/linux/sigrand5120-2.6/Makefile
		;;
	    *) usage;;
   esac
   shift
fi

rm -f .config* .tmpconfig.h
cp -a config_$oem .config

if test -n "$nofw"; then
echo "Unset FW in .config"
sed -i -r -e 's/^.*(BR2_PACKAGE_KMOD_ARPTABLES)=./\1=n/g'	.config
sed -i -r -e 's/^.*(BR2_PACKAGE_KMOD_EBTABLES)=./\1=n/g'	.config
sed -i -r -e 's/^.*(BR2_PACKAGE_KMOD_IPT.*)=./\1=n/g'		.config
sed -i -r -e 's/^.*(BR2_PACKAGE_KMOD_IMQ.*)=./\1=n/g'		.config
sed -i -r -e 's/^.*(BR2_PACKAGE_KMOD_IP6TABLES)=./\1=n/g'	.config
sed -i -r -e 's/^.*(BR2_COMPILE_IPTABLES)=./\1=n/g'		.config
sed -i -r -e 's/^.*(BR2_PACKAGE_IPTABLES.*)=./\1=n/g'		.config
sed -i -r -e 's/^.*(BR2_PACKAGE_IP6TABLES)=./\1=n/g'		.config
fi

yes '' | make oldconfig > oldconfig-${oem}${nofw}-$$.log
make oem_clean

if test -e .cfg.sg-17r; then
   .     ./.cfg.sg-17r
   #echo ".cfg.sg-17r exists, NOFW: $NOFW, nofw: $nofw"
else
   echo "NOFW=$nofw" > .cfg.sg-17r
   #echo "create .cfg.sg-17r, NOFW: $NOFW, nofw: $nofw"
   NOFW=_0_ # force 'NOFW != nofw' at first time
fi

if test "$NOFW" != "$nofw"; then
    make target/linux-clean

    echo "NOFW=$nofw" > .cfg.sg-17r
    #echo "update .cfg.sg-17r, NOFW: $NOFW, nofw: $nofw"
fi


nice -19 make V=9 || exit 1

rev=`./rev.sh`
mv	bin/openwrt-sigrand5120-2.6-jffs2-32MB.bin \
	sg17-r-cp1_${rev}${nofw}_${oem}.bin

