#!/bin/sh

cfg=./.cf-sg

`dirname $0`/cf-sg "$@" || exit $?

. $cfg

if test "$OEM_OLD" != "$OEM_CUR"; then
   echo "OEM clean"
   make oem_clean
fi

if test "$NOFW_OLD" -ne "$NOFW_CUR"; then
   echo "LINUX clean"
   make target/linux-clean
fi

nice -19 make V=9 $MAKE_TARGET
