#!/bin/sh

pn=`basename $0`
usage()
{
   echo 1>&2 "Usage: $pn [-v] package target [target...]"
   exit 1
}

if test "$#" -lt 2; then
   usage
fi


case $1 in
   -v) V=99; shift;;
esac

if test -n "$V"; then
   _v_="V=${V}"
else
   _v_=
fi


pkg=$1; shift

for t in "$@"; do
	make ${_v_} package/${pkg}-${t} || exit 1
done
