#!/bin/sh

 origin=ssh://git@sigrand.ru/midge.git

if test "`id -un`" = "df"; then
   live=ssh://live.1nsk.ru/home/df/siggit/midge.git
fi

echo
repos="$origin $live"
for r in $repos; do
	echo "======== $r"
	git push "$@" $r
done
echo
