#!/bin/sh

. /etc/templates/oem-vars

case $1 in
	start)
		for s in `kdb get sys_pcitbl_slots`; do
			type=`kdb get sys_pcitbl_s${s}_iftype`
			if [ "$type" = "$mr17s_drvname" ]; then
				echo "Starting tbuff"
				logger "tbuff: Starting"
				/sbin/tbuffd
				return
			fi
		done
	;;
	stop)
		echo "Stopping tbuff"
		logger "tbuff: Stopping"
		killall tbuffd
	;;
	restart)
		$0 stop
		usleep 100000
		$0 start
	;;
	*)
		echo "tbuff: wrong command: $1"
		exit 1
	;;
esac
