#!/bin/sh

PORTSINFO="/proc/driver/sgatab/channels"

gen_config()
{
	/etc/templates/Update voip
}

case "$1" in
start)
	# set presence of VoIP module to 0
	kdb set sys_voip_present=0

	# Testing module presence
	card_present=`cat /proc/pci | grep 0055:009c | wc -l`

	# if not existing - unload modules
	if test $card_present <> 0; then
		echo -n "Starting VoIP services:" 

		/bin/svi
		
		# find VoIP module
		if [ -r $PORTSINFO ]; then
			porttype=`head -n1 $PORTSINFO | awk -F ':' '{print $2}'`
			if [ "$porttype" != "UNDEFINED" ]; then
				kdb set sys_voip_present=1
				gen_config
			fi
		fi

		killall svd 2>/dev/null
		/bin/svd

		echo " OK"
	fi
;;
stop)
	echo -n "Stoping VoIP daemon:"
	killall svd 2>/dev/null
	echo " OK"
;;
restart)
	# check that VoIP module is installed
	if [ "x$(kdb get sys_voip_present)" = "x1" ]; then
		killall svd 2>/dev/null
		/bin/svd
	fi
;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
;;
esac

exit 0
