#!/bin/sh

DEFAULT=/etc/default/snmpd
LIB_D=/var/lib/snmp
LOG_D=/var/log
RUN_D=/var/run
PID_F=$RUN_D/snmpd.pid

[ -f $DEFAULT ] && . $DEFAULT

case $1 in
 start)
  [ -d $LIB_D ] || mkdir -p $LIB_D
  [ -d $LOG_D ] || mkdir -p $LOG_D
  [ -d $RUN_D ] || mkdir -p $RUN_D
  enabled=`kdb get sys_snmpd_enable`
  if [ "$enabled" == "1" ]; then
   options=`kdb get sys_snmpd_cmd`
   snmpd $options
  fi
  ;;
 stop)
  killall snmpd
  ;;
 *)
  echo "usage: $0 (start|stop)"
  exit 1
esac
exit $?
