#!/bin/sh


. /etc/templates/lib

iface_tmpl()
{
    local enabled;      # all
    local type;         # all
    local ipaddr;       # static
    local netmask;      # static
    local broadcast;    # static
    local hwaddress;    # static
    local mtu;          # static
    local hostname;     # udhcpc, pump, dhcpcd
    local leasehours;   # pump
    local vendor;       # dhcpcd
    local leasetime;    # dhcpcd
    local clientid;     # udhcpc, dhcpcd 
    local provider;     # ppp, wvdial


    eval `kdb sls "sys_iface_${iface}_"`

    [ "$enabled" = "1" ] && \
        echo "auto $iface"
    # STATIC
    if [ "$type" = "static" ]; then
        is_ipaddress "$ipaddr" || die "Bad ipaddress $ipaddr"
        is_ipaddress "$netmask" || die "Bad netmask $netmask"

        echo "iface $iface inet static"
        echo "  address $ipaddr"
        echo "  netmask $netmask"
        [ "$broadcast" ] && \
            echo "  broadcast $broadcast"
        [ "$hwaddr" ] && \
            echo "  hwaddress $hwaddr"
        [ "$mtu" ] && \
            echo "  mtu $mtu"

    # DHCP
    elif [ "$type" = "dhcp" ]; then
        echo "iface $iface inet dhcp"

        [ "$hostname" ] && \
            echo "  hostname $hostname"
        [ "$leasetime" ] && \
            echo "  leasetime $leasetime"
        [ "$leasehours" ] && \
            echo "  leasehours $leasehours"
        [ "$vendor" ] && \
            echo "  vendor $vendor"
        [ "$clientid" ] && \
            echo "  clientid $clientid"

    # LOOPBACK
    elif [ "$type" = "loopback" ]; then
        echo "iface $iface inet loopback"

    # EMPTY type
    elif [ -z "$type" ]; then
        echo "# iface $iface does not have a type"

    # Something else
    else 
        echo "# bad iface $type type see: kdb get sys_iface_${iface}_type";
    fi
}
#echo "auto lo"
#echo "iface lo loopback"
#echo

show_header $0

for iface in `kdb get sys_ifaces`; do 
    iface_tmpl $iface
    echo
done

