#!/bin/sh

. /etc/templates/lib

show_header

secrets=`kdb get sys_dialin_secrets`

if [ "$secrets" == "chap" ]; then
    rm /etc/ppp/options -f
    echo nocrtscts
    echo require-chap
else
    rm /etc/ppp/options -f
    echo nocrtscts
fi
