#!/bin/sh


VERBOSE=2
CMD_VERBOSE=1

die () {
	echo $@ >&2
	exit 1;
}

warn () {
	echo "Warning: "$@ >&2
}
required(){
    local prg=`which $1`
    test -x "$prg" || die "$0: Error $1 is required"
}

info(){
	local level=$1
	shift
	[ $level -le $VERBOSE ] && echo Info: "$@" >&2
}

cmd(){
	[ $CMD_VERBOSE -gt 0 ] && echo "$*"
	$@
}


