#!/bin/sh


eval `kdb -q ls hw_adm5120sw`

for vlan in 0 1 2 3 4 5; do
	var="\$hw_adm5120sw_vlan${vlan}"
	value="`eval echo $var`"
	if [ -n "$value" -a -f /proc/sys/net/adm5120sw/vlan${vlan} ]; then
		echo -n "Setting vlan${vlan} ..." 
		echo $value >/proc/sys/net/adm5120sw/vlan${vlan}
		echo "done."
	fi
done
