#!/bin/sh

modprobe dslam_gpio

tmp=`dslam_debug 0 00`
let "n=${#tmp}-3"
let "m=${#tmp}+1"
tmp2=`expr substr $tmp $n $m`

kdb rm sys_dslam_card

if [ "$tmp2" = "ffff" ]; then
	kdb set sys_dslam_card=0
	rmmod dslam_gpio
else
	kdb set sys_dslam_card=1
	# statistic config
	dslam_debug 0 3b ffff
	dslam_debug 0 3c 07ff
	dslam_debug 0 01 0612
	
	dslam_debug 1 3b ffff
	dslam_debug 1 3c 07ff
	dslam_debug 1 01 0612
	
	#force TP
	dslam_debug 0 ff 0008
	dslam_debug 1 ff 0008
	
	#set up RGMII
	dslam_debug 0 f9 1e38
	dslam_debug 1 f9 1e38
	
	#force link
	dslam_debug 0 d8 ffff
	dslam_debug 1 d8 ffff
	dslam_debug 0 d9 37ff
	dslam_debug 1 d9 17ff
fi
