#!/bin/sh

. /etc/templates/oem-vars

kdb="kdb"
e1_cfg="/sys/bus/pci/drivers/"${mr16g_drvname}
ifcfg="/sbin/ifconfig"

. /etc/templates/sigrand-lib

_e1_mr16ifdefcfg(){	
	local slot=$1
	local dev=$2	
	kdb rm sls sys_pcicfg_s${slot}_${dev}*
	kdb set sys_pcicfg_s${slot}_${dev}_proto="cisco"
	kdb set sys_pcicfg_s${slot}_${dev}_fram="0"
	kdb set sys_pcicfg_s${slot}_${dev}_ts16="1"
	kdb set sys_pcicfg_s${slot}_${dev}_smap=""
	kdb set sys_pcicfg_s${slot}_${dev}_crc4="0"
	kdb set sys_pcicfg_s${slot}_${dev}_cas="0"
	kdb set sys_pcicfg_s${slot}_${dev}_clk="0"
	kdb set sys_pcicfg_s${slot}_${dev}_lhaul="0"
	kdb set sys_pcicfg_s${slot}_${dev}_lcode="1"
	kdb set sys_pcicfg_s${slot}_${dev}_hcrc="1"
	kdb set sys_pcicfg_s${slot}_${dev}_fill="1"	
	kdb set sys_pcicfg_s${slot}_${dev}_inv="normal"
}

_dsl_mr16defcfg(){
	local slot=$1
	local ifnum=`kdb get sys_pcitbl_s${slot}_ifnum`
	local i=0

	kdb set sys_pcicfg_s${slot}_ifnum="$ifnum"
	while [ $i -lt $ifnum ]; do
		_e1_mr16ifdefcfg $slot $i
		i=`expr $i + 1`
	done
}

_e1_ifcfg(){
	local iface=$1
	local slot=$2
	local dev=$3
	unset proto fram ts16 smap crc4 cas clk lhaul lcode hcrc inv fill 
	eval `$kdb -qq sls sys_pcicfg_s${slot}_${dev}_`
	# apply configuration
	$ifcfg $iface down
	# bind driver with protocol
	case "${proto}" in
	hdlc*)
		sethdlc $iface $proto ${hdlc_enc} ${hdlc_parity}
		;;
	cisco)
		if [ "${cisco_int}" -eq "0" ]; then
			cisco_int=""
		elif [ -z "${cisco_int}" ]; then
			cisco_int=""		
		else
			cisco_int="interval ${cisco_int}"
		fi
		if [ "${cisco_to}" = 0 ]; then
			cisco_to=""
		elif [ -z "${cisco_to}" ]; then
			cisco_to=""		
		else
			cisco_to="timeout ${cisco_to}"
		fi
		sethdlc $iface $proto ${cisco_int} ${cisco_to}
		;;
	*)
		if [ -n "$proto" ]; then
		    sethdlc $iface $proto
		fi
	esac
	# set network interface proto (for web)
	case "$proto" in
	hdlc-eth)
		kdb set sys_iface_${iface}_proto=ether
		;;
	*)
		kdb set sys_iface_${iface}_proto=hdlc
		;;
	esac
	DIR=`pwd`
	cd $e1_cfg/$iface

	# Change slotmap only if it really changed
	
	echo $fram 	> framed
	if [ "$fram" = "1" ]; then
		smap_old=`cat slotmap`
		echo $ts16 	> map_ts16
		if [ "$smap_old" != "$smap" ]; then
			echo "$smap" > slotmap
		fi
		smap=`cat slotmap`
		kdb set sys_pcicfg_s${slot}_${dev}_smap=$smap
	fi
	echo $clk 	> clck
	echo $crc4 	> crc4
	# CAS depends on TS16 (it uses TIMESLOT#16 - so update from hardware)
	echo $cas 	> cas
	tmp=`cat cas`
	if [ "$tmp" = "on" ]; then
		kdb set sys_pcicfg_s${slot}_${dev}_cas=1
	else
		kdb set sys_pcicfg_s${slot}_${dev}_cas=0
	fi
	echo $lhaul > long_haul
	echo $lcode	> hdb3
	echo $hcrc	> crc16
	echo $fill	> fill_7e
	echo $inv	> inv
	cd $DIR
	enabled=`kdb get sys_iface_${iface}_enabled`
	[ "$enabled" -eq 1 ] && $ifcfg $iface up
}

_e1_modcfg(){
	local slot=$1
	local dev=$2
	local ifaces
	local ifnum
	local iface
	
	type=`kdb get sys_pcicfg_s${slot}_iftype`
	cur_cnt=`kdb get sys_pcitbl_s${slot}_ifnum`
	cfg_cnt=`kdb get sys_pcicfg_s${slot}_ifnum`
	if [ -z "$type" ]; then
		kdb set sys_pcicfg_s${slot}_iftype="$mr16g_drvname"
		_e1_mr16defcfg $slot
	elif [ "$cur_cnt" -gt "$cfg_cnt" ]; then
		tmp=`expr $cfg_cnt + 1`
echo "Create def configurations for $type: $tmp-"`expr $cur_cnt - 1`
		while [ "$tmp" -lt "$cur_cnt" ]; do
			_e1_mr16ifdefcfg "$slot" "$tmp"
		done
	fi
	
	ifaces=`kdb get sys_pcitbl_s${slot}_ifaces`
	ifnum=0
	for iface in $ifaces; do
		if [ -n "$dev" ]; then
			if [ "$dev" -eq "$ifnum" ]; then
				_e1_ifcfg $iface $slot $ifnum
				break
			fi
		else
			_e1_ifcfg $iface $slot $ifnum
		fi
		ifnum=`expr $ifnum + 1`
	done
}

	
_e1_start(){
	
	echo -n "Configuring E1: "
	eval `kdb sls -q sys_pcitbl_`
	for s in $slots; do
		unset type
		eval "type=\$s${s}_iftype"
		if [ "$type" != "$mr16g_drvname" ]; then
			continue
		fi
	    _e1_modcfg $s
		echo "$s "
	done
	echo
}
 
_e1_stop(){
	return 0
}

_e1_restart(){
	_e1_ifcfg $1 $2
}

case "$1" in
	start) 
		_e1_start 
		;;
	stop)
		_e1_stop 
		;;
	restart)
		_e1_modcfg $2 $3
		;;
esac
