#!/bin/sh


_ifup(){
	local iface=$1
	eval `kdb -qq sls sys_iface_${iface}_`
	[ -z $type ] && echo "sys_iface_${iface}_type is not set"
	echo -n "Setting up $iface "
	case $type in
	static)
		opts="$real $ipaddr netmask $netmask"
		[ -n "$broadcast" ] && opts="$opts broadcast $broadcast"
		/sbin/ifconfig $opts
		[ -n "$gateway" ] && route add default gw $gateway 
		;;
	dhcp)
		eval `kdb -qq ls sys_hostname`
		opts=" -i $real --hostname=$sys_hostname --background -p /var/run/udhcpc.$iface.pid"
		/sbin/udhcpc $opts 
		;;
	pppoe)
		;;
	pptp)
		;;
	ipsec)
		;;
	esac
	echo " done."
	eval `kdb -qq ls sys_ntpclient_`
	if [ "$sys_ntpclient_enabled" = "1" -a -x /usr/sbin/ntpclient ]; then
		/sbin/route -n | grep ^0.0.0.0 >/dev/null && /usr/sbin/ntpclient -c 1 -s -h ${sys_ntpclient_server:-pool.ntp.org}
	fi
}

_ifdown(){
	local iface=$1
	eval `kdb -qq sls sys_iface_${iface}_`
	[ -z $type ] && echo "sys_iface_${iface}_type is not set" && exit 1
	echo -n "Setting down $iface: "
	/sbin/ifconfig $iface down
	case $type in
	static)
		;;
	dhcp)
		[ -r "/var/run/udhcpc.$iface.pid" ] && kill `cat /var/run/udhcpc.$iface.pid`
		;;
	pppoe)
		;;
	pptp)
		;;
	ipsec)
		;;
	esac
	echo " done."
}

case "$0" in
	*network)
		# starts all ifaces
		eval `kdb -q ls sys_iface`
		for iface in $sys_ifaces; do
			eval `kdb -qq sls sys_iface_${iface}_`
			[ "$1" = "start" -a "$auto" != "0" ] && _ifup $iface
			[ "$1" = "stop" ] && _ifdown $iface
			if [ "$1" = "restart" ]; then
				_ifdown $iface
				_ifup $iface 
			fi
		done
		;;
	*ifup)
		[ "x$1" = "x-a" ] && /etc/init.d/network start || _ifup $1
		;;
	*ifdown)
		[ "x$1" = "x-a" ] && /etc/init.d/network stop || _ifdown $1
		;;
	esac



