#!/bin/sh

if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "" ]; then
	echo "Usage "`basename $0`" <slot> reg [val]"
	echo "         slot = 0-3"
	echo "         slots numbering:"
	echo -e "         \t0 2"
	echo -e "         \t1 3"
	return
fi

if [ "$1" -lt "0" -o "$1" -gt "3" ]; then
	echo "Usage "`basename $0`" <slot> reg [val]"
	echo "         slot = 0-3"
	echo "         slots numbering:"
	echo -e "         \t0 2"
	echo -e "         \t1 3"
fi
slot=$(($1+2))
shift
if [ "$2" = "" ]; then
	echo "$1 1" > /proc/sys/debug/$slot/read
	cat /proc/sys/debug/$slot/read
else
	echo "$1 $2" > /proc/sys/debug/$slot/write
fi
