#!/bin/sh

if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "" ]; then
	echo "Usage "`basename $0`" <slot> <poe_chip> reg [val]"
	echo "         slot = 0-3; poe_chip = 0-1"
	return
fi

if [ "$1" -lt "0" -o "$1" -gt "3" ]; then
	echo "Usage "`basename $0`" <slot> <poe_chip> reg [val]"
	echo "         slot = 0-3; poe_chip = 0-1"
	return
fi
slot=$(($1+2))
shift
chip=$1
shift
if [ "$2" = "" ]; then
	echo "$chip $1 1" > /proc/sys/debug/$slot/poe_read
	cat /proc/sys/debug/$slot/poe_read
else
	echo "$chip $1 $2" > /proc/sys/debug/$slot/poe_write
fi
