CFLAGS+=@CFLAGS@
obj-m := @DRVNAME@.o
@DRVNAME@-objs := mr16g_hdlc.o

@DRVNAME@.ko: mr16g_hdlc.c
	make -C @KERNSRC@ SUBDIRS=$(PWD) modules CROSS_COMPILE=@CROSS_PREFIX@

all: @DRVNAME@.ko

install: @DRVNAME@.ko
	install -m 600 @DRVNAME@.ko @INST_PATH@/lib/modules/@KERNVER@/
	install -m 700 ./tools/mr16gcfg @INST_PATH@/sbin/@TOOLNAME@
	[ "yes" != "@DEBUG@" ] || install -m 744 ./tools/mr16g_debug @INST_PATH@/sbin

clean:
	rm --preserve-root -f .*.o*
	rm --preserve-root -f .*.ko*
	rm --preserve-root -f *.o*
	rm --preserve-root -f *.ko*
	rm --preserve-root -f *.mod.*
	rm --preserve-root -f .sg16*
	rm --preserve-root -f -R .tmp*



