#!/bin/sh

kdb="kdb"
ifcfg="/sbin/ifconfig"
priv_dir="ms_private"

. /etc/templates/oem-vars

mam17h_cfg="/sbin/${mam17h_modname}_cfg"
mam17h_drvname=${mam17h_modname}

# checks that DSL service is enabled

# Device configurations
_dsl_mam17hifdefcfg(){
	local slot=$1
	local dev=$2
	kdb rm sls sys_pcicfg_s${slot}_${dev}*
	kdb set sys_pcicfg_s${slot}_${dev}_advlink="off"
	kdb set sys_pcicfg_s${slot}_${dev}_mode="slave"
	kdb set sys_pcicfg_s${slot}_${dev}_clkmode="sync"
	kdb set sys_pcicfg_s${slot}_${dev}_rate="768"
	kdb set sys_pcicfg_s${slot}_${dev}_code="tcpam32"
	kdb set sys_pcicfg_s${slot}_${dev}_annex="A"
	kdb set sys_pcicfg_s${slot}_${dev}_fill="fill_ff"
}

_dsl_mam17hdefcfg(){
	local slot=$1
	local ifnum=`kdb get sys_pcitbl_s${slot}_ifnum`
	local iftype=`kdb get sys_pcitbl_s${slot}_iftype`
	local i=0

	kdb set sys_pcicfg_s${slot}_ifnum="$ifnum"
	while [ $i -lt $ifnum ]; do
		_dsl_mam17hifdefcfg $slot $i
		i=$(( $i + 1 ))
	done
}

_dsl_mam17hifcfg(){
	local iface=$1
	local slot=$2
	local index=$3

	# Hardware settings
	eval `$kdb -qq sls sys_pcicfg_s${slot}_${ifnum}_`
	eval `$kdb -qq sls sys_pcicfg_s${slot}_pw`
	pwron="pwroff"
	case "$ifnum" in
		0)
			if [ "$r_0_on" = "pwron" ]; then
				pwron="pwron";
			fi
		;;
		1)
			if [ "$r_0_on" = "pwron" ]; then
				pwron="pwron";
			fi
		;;
		2)
			if [ "$r_1_on" = "pwron" ]; then
				pwron="pwron";
			fi
		;;
		3)
			if [ "$r_1_on" = "pwron" ]; then
				pwron="pwron";
			fi
		;;
	esac
	if [ -n "$advlink" ]; then
		advlink="advlink $advlink"
	fi
	advlink=""

	if [ "$pbomode" = "on" -o "$pbomode" = "1" ]; then
		pbo="pbo-forced"
		[ -z "$pboval" ] && pboval=0 && \
				kdb set sys_pcicfg_s${slot}_${ifnum}_pboval=0
		echo "$pboval" > /sys/class/net/$iface/$priv_dir/pbo_val
		pboval=`cat  /sys/class/net/$iface/$priv_dir/pbo_val`
		kdb set sys_pcicfg_s${slot}_${ifnum}_pboval=$pboval
		pbo="$pbo $pboval"
	else
		pbo="pbo-normal"
	fi

	# apply configuration
	on_off=`kdb get sys_pcicfg_s${slot}_${ifnum}_on`
	if [ "$on_off" != "0" ]; then
		if [ "$mode" == "slave" ]; then
   			$mam17h_cfg $iface $mode $pwron
		else
			if [ "$rate" == "-1" -a -n "$mrate" ]; then
				rate="rate $mrate"
			else
				[ -n "$rate" ] && rate="rate $rate"
			fi

	   		[ -n "$annex" ] && annex="annex $annex"
	    		$mam17h_cfg $iface $mode $rate $code $annex \
				$pwron $pbo > /dev/null
			# Correct rate setted by hands
	    		rate=`cat  /sys/class/net/$iface/$priv_dir/rate`
			pboval=`cat  /sys/class/net/$iface/$priv_dir/pbo_val`
			[ -n "$mrate" ] && kdb set sys_pcicfg_s${slot}_${ifnum}_mrate=$rate
		fi
	else
		echo "0" > /sys/class/net/$iface/$priv_dir/on_off
	fi
}

_dsl_mam17hcfg(){
	local slot=$1
	local dev=$2
	local ifaces
	local ifnum=0
	local iface

	ifaces=`kdb get sys_pcitbl_s${slot}_ifaces`
	type=`kdb get sys_pcicfg_s${slot}_iftype`
	# Check changing in number of channels
	cur_cnt=`kdb get sys_pcitbl_s${slot}_ifnum`
	cfg_cnt=`kdb get sys_pcicfg_s${slot}_ifnum`
	if [ -z "$type" ]; then
		kdb set sys_pcicfg_s${slot}_iftype="$mam17h_drvname"
		kdb set sys_pcicfg_s${slot}_ifaces="$ifaces"
		_dsl_mam17hdefcfg $slot
	elif [ "$cur_cnt" -gt "$cfg_cnt" ]; then
		tmp="$cfg_cnt"
		while [ "$tmp" -lt "$cur_cnt" ]; do
			_dsl_mam17hifdefcfg "$slot" "$tmp"
			tmp=$(( $tmp + 1 ))
		done
	fi
	kdb set sys_pcicfg_s${slot}_ifnum=$cur_cnt

	ifaces=`kdb get sys_pcitbl_s${slot}_ifaces`
	for iface in $ifaces; do
		if [ -n "$dev" ]; then
			if [ "$dev" -eq "$ifnum" ]; then
				_dsl_mam17hifcfg "$iface" "$slot" "$dev"
				break
			fi
		else
			_dsl_mam17hifcfg "$iface" "$slot" "$ifnum"
		fi
		if [ "$slot" = "0002" ]; then
			$kdb set sys_iface_${iface}_sw=0
			$kdb set sys_iface_${iface}_sw_port=$ifnum
			$kdb set sys_iface_${iface}_slot=0
			$kdb set sys_iface_${iface}_port=$ifnum
		fi
		if [ "$slot" = "0003" ]; then
			$kdb set sys_iface_${iface}_sw=0
			$kdb set sys_iface_${iface}_sw_port=$(( $ifnum + 8 ))
			$kdb set sys_iface_${iface}_slot=1
			$kdb set sys_iface_${iface}_port=$ifnum
		fi
		if [ "$slot" = "0004" ]; then
			$kdb set sys_iface_${iface}_sw=1
			$kdb set sys_iface_${iface}_sw_port=$ifnum
			$kdb set sys_iface_${iface}_slot=2
			$kdb set sys_iface_${iface}_port=$ifnum
		fi
		if [ "$slot" = "0005" ]; then
			$kdb set sys_iface_${iface}_sw=1
			$kdb set sys_iface_${iface}_sw_port=$(( $ifnum + 8 ))
			$kdb set sys_iface_${iface}_slot=3
			$kdb set sys_iface_${iface}_port=$ifnum
		fi

		ifnum=$(( $ifnum + 1 ))
	done
}

_dsl_start(){

	dslam_card=`kdb get sys_dslam_card`
	if [ "$dslam_card" != "1" ]; then
		return 0
	fi
	#apply defconfig if no configuration
	echo "Configuring DSLAM SHDSL: "
	eval `kdb sls -q sys_pcitbl_`
	for s in $slots; do
		unset type num ifaces
		eval "type=\$s${s}_iftype"
		eval "num=\$s${s}_ifnum"
		eval "ifaces=\$s${s}_ifaces"

		if [ "$type" != "$mam17h_drvname" ]; then
			continue
		fi

	        _dsl_mam17hcfg $s

		unset ver pfx iface
		iface=`echo "$ifaces" |  awk '{print $(1)}' `
		pwr=`cat  /sys/class/net/$iface/$priv_dir/pwr_source`
                if [ "$pwr" = "1" ]; then
                    $kdb set sys_pcicfg_s${s}_pwr_source=1
                else
			kdb rm sys_pcicfg_s${s}_pwr_source
                fi
		echo "    $ifaces "
	done
	echo
}

_dsl_stop(){

	# stop all interfaces
	for iface in `$kdb get sys_dsl_ifaces`; do
		_dsl_if_stop $iface
	done

	# stop driver
	_dsl_stop_drv

	# stop service
	_dsl_stop_svc
}

case "$1" in
	start)
		_dsl_start ;;
	stop)
		_dsl_stop ;;
	restart)
	    _dsl_mam17hcfg $2 $3
esac
