#!/bin/sh

kdb="kdb"
priv_dir="ms_private"

. /etc/templates/oem-vars

_start() {
	eval `kdb sls -q sys_pcitbl_`
	dslam_card=`kdb get sys_dslam_card`
	if [ "$dslam_card" != "1" ]; then
		exit 0
	fi
	echo "Configuring DSLAM Ethernet: "
	cmd=""
	for s in $slots; do
		unset type num ifaces
		eval "type=\$s${s}_iftype"
		eval "num=\$s${s}_ifnum"
		eval "ifaces=\$s${s}_ifaces"

		if [ "$type" != "$ms17e_modname" -a "$type" != "$ms17e_v2_modname" ]; then
			continue
		fi
		local ifnum=0
		for iface in $ifaces; do
			if [ "$s" = "0002" ]; then
				$kdb set sys_iface_${iface}_sw=0 : set sys_iface_${iface}_sw_port=$((7 - $ifnum)) : set sys_iface_${iface}_slot=0 : set sys_iface_${iface}_port=$ifnum
				slot=0
			fi
			if [ "$s" = "0003" ]; then
				$kdb set sys_iface_${iface}_sw=0 : set sys_iface_${iface}_sw_port=$((15 - $ifnum)) : set sys_iface_${iface}_slot=1 : set sys_iface_${iface}_port=$ifnum
				slot=1
			fi
			if [ "$s" = "0004" ]; then
				$kdb set sys_iface_${iface}_sw=1 : set sys_iface_${iface}_sw_port=$((7 - $ifnum)) : set sys_iface_${iface}_slot=2 : set sys_iface_${iface}_port=$ifnum
				slot=2
			fi
			if [ "$s" = "0005" ]; then
				$kdb set sys_iface_${iface}_sw=1 : set sys_iface_${iface}_sw_port=$((15 - $ifnum)) : set sys_iface_${iface}_slot=3 : set sys_iface_${iface}_port=$ifnum
				slot=3
			fi

			if [ "$type" = "$ms17e_modname" ]; then

			unset on flow duplex rate auto pwr_auto pwr_auto_off pwr_current pwr_on pwr_poe_plus pwr_class
			cmd="$cmd port fe${slot}/${ifnum} "
			eval `kdb -lqq sls sys_dslam_${iface}_`
			if [ "$on" = "0" ]; then
				cmd="$cmd off \\n"
				cmd="$cmd power off \\n"
			else
				cmd="$cmd on \\n"
				if [ "$pwr_auto" != "0" ]; then
					if [ "$pwr_auto" == "1" ]; then
						if [ "${pwr_poe_plus}" == "1" ]; then
							cmd="$cmd poe_config auto poe+ \\n"
						else
							cmd="$cmd poe_config auto \\n"
						fi
#						echo "port fe${slot}/${ifnum} poe_config auto"
					else # where is no config yet, set it to default
						kdb set sys_dslam_fe${slot}${ifnum}_pwr_auto=1
						kdb set sys_dslam_fe${slot}${ifnum}_pwr_poe_plus=0
						kdb set sys_dslam_fe${slot}${ifnum}_pwr_on=1
						pwr_on="1"
						cmd="$cmd poe_config auto \\n"
					fi
				else
					cmd="$cmd poe_config class $pwr_class \\n"
#					echo "port fe${slot}/${ifnum} poe_config class $pwr_class"
				fi
				if [ "$pwr_on" = "1" ]; then
					cmd="$cmd power on \\n"
				else
					cmd="$cmd power off \\n"
				fi
			fi

			else # type = ms17e_v2
				# ms17e_v2 store configs in module so we need set it in kdb
				echo "${ifnum} 3" > /proc/sys/net/ethernet/fe${slot}/poe
				poe="`cat /proc/sys/net/ethernet/fe${slot}/poe`"
				status="${poe##*: }"
				status=${status%% *}
				if [ "${status}" = "Enabled" ]; then
					kdb set sys_dslam_fe${slot}${ifnum}_pwr_on=1
				else
					kdb set sys_dslam_fe${slot}${ifnum}_pwr_on=0
				fi
				pmax="`cat /proc/sys/net/ethernet/fe${slot}/pmax`"
				pmax="${pmax##*: }"
				pmax="${pmax%% W*}"
				let "i=0"
				for pmaxi in ${pmax}; do
					if [ "$i" = "${ifnum}" ]; then
						pmax="$pmaxi"
						break;
					fi
					let "i=i+1"
				done
				kdb set sys_dslam_fe${slot}${ifnum}_pmax=${pmax}
				pmax_total="`cat /proc/sys/net/ethernet/fe${slot}/pmax`"
				pmax_total="${pmax_total##*Pmax_total=}"
				pmax_total="${pmax_total%%W*}"
				kdb set sys_dslam_${s}_pmax_total=${pmax_total}
			fi

			if [ "$flow" = "0" ]; then
				cmd="$cmd flow off \\n"
			else
				cmd="$cmd flow on \\n"
			fi
			if [ "$duplex" = "0" ]; then
				cmd="$cmd duplex half \\n"
			else
				cmd="$cmd duplex full \\n"
			fi
			if [ "$rate" = "10" ]; then
				cmd="$cmd rate 10 \\n"
			else
				cmd="$cmd rate 100 \\n"
			fi
			if [ "$auto" != "0" ]; then
				cmd="$cmd auto \\n"
			fi
			cmd="$cmd cd \\n"
			ifnum=$(( $ifnum + 1 ))
		done

		if [ "$type" = "$ms17e_modname" ]; then

		unset ver pfx iface
		iface=`echo "$ifaces" |  awk '{print $(1)}' `
		pwr=`cat  /sys/class/net/$iface/$priv_dir/pwr_source`
		for tmp in $ifaces; do
			$kdb set sys_dslam_${tmp}_type=1
		done

		else # type = ms17e_v2
			let "slot=${s}-2"
			pwr=`cat /proc/sys/net/ethernet/fe${slot}/pwr_source`
			for tmp in $ifaces; do
				$kdb set sys_dslam_${tmp}_type=2
			done
		fi

		if [ "$pwr" = "1" ]; then
			$kdb set sys_pcicfg_s${s}_pwr_source=1
			for tmp in $ifaces; do
				$kdb set sys_dslam_${tmp}_pwr_source=1
			done
		else
			kdb rm sys_pcicfg_s${s}_pwr_source
			for tmp in $ifaces; do
				kdb rm sys_dslam_${tmp}_pwr_source
			done
		fi

		echo "    $ifaces "
	done
#	echo "$cmd"
	if [ "$cmd" != "" ]; then
		cli $cmd
	fi
#	echo ""
}

_stop() {
	#TODO
	qwe=qwe
}

_restart() {
	if [ "$1" = "4" ]; then
		/etc/init.d/dslam_sw update_cfg uplinks
		return 0
	fi
	slot=$(($1-2))
	port=$2

	unset on flow duplex rate auto pwr_auto pwr_auto_off pwr_current pwr_on pwr_poe_plus pwr_class
	cmd="$cmd port fe${slot}/${port} "
	eval `kdb -lqq sls sys_dslam_fe${slot}${port}_`

	if [ "$type" = "$ms17e_modname" ]; then

	if [ "$on" = "0" ]; then
		cmd="$cmd off \\n"
		cmd="$cmd power off \\n"
	else
		cmd="$cmd on \\n"
		if [ "$pwr_auto" != "0" ]; then
			if [ "${pwr_poe_plus}" == "1" ]; then
				cmd="$cmd poe_config auto poe+ \\n"
			else
				cmd="$cmd poe_config auto \\n"
			fi
		else
			cmd="$cmd poe_config class $pwr_class \\n"
		fi
		if [ "$pwr_on" = "1" ]; then
			cmd="$cmd power on \\n"
		else
			cmd="$cmd power off \\n"
		fi
	fi

	else # type = ms17e_v2

	if [ "$on" = "0" ]; then
		cmd="$cmd off \\n"
#		cmd="$cmd power off \\n"
	else
		cmd="$cmd on \\n"
	fi
	if [ "$pwr_on" = "1" ]; then
		echo "${port} 1" > /proc/sys/net/ethernet/fe${slot}/poe
#		cmd="$cmd power on \\n"
	else
		echo "${port} 0" > /proc/sys/net/ethernet/fe${slot}/poe
#		cmd="$cmd power off \\n"
	fi
	pmax=`kdb get sys_dslam_fe${slot}${port}_pmax`
	pmax_total=`kdb get sys_dslam_${1}_pmax_total`
	echo "${port} ${pmax}" > /proc/sys/net/ethernet/fe${slot}/pmax
	echo "${pmax_total}" > /proc/sys/net/ethernet/fe${slot}/pmax_total

	fi

	if [ "$flow" = "0" ]; then
		cmd="$cmd flow off \\n"
	else
		cmd="$cmd flow on \\n"
	fi
	if [ "$duplex" = "0" ]; then
		cmd="$cmd duplex half \\n"
	else
		cmd="$cmd duplex full \\n"
	fi
	if [ "$rate" = "10" ]; then
		cmd="$cmd rate 10 \\n"
	else
		cmd="$cmd rate 100 \\n"
	fi
	if [ "$auto" != "0" ]; then
		cmd="$cmd auto \\n"
	fi

	if [ "$cmd" != "" ]; then
		cli $cmd
	fi
}
case "$1" in
	start)
		_start
	;;
	stop)
		_stop
	;;
	restart)
		if [ "$2" != "" -a "$3" != "" ]; then
			_restart $2 $3
		else
			_stop
			_start
		fi
	;;
esac
