TOP_DIR     ?= .
BUILD_TYPE   = MULTI_SRC_BIN
BIN_NAME     = rs232-tcpdmx
LIBS         = lockdev pthread

CFLAGS_      = -std=gnu99 #-fgnu89-inline
CFLAGS_     += -Wno-inline

#Q=

include $(TOP_DIR)/rules.make
