#ifndef _DRV_TAPI_LL_INTERFACE_VERSION_H
#define _DRV_TAPI_LL_INTERFACE_VERSION_H
/******************************************************************************

                               Copyright (c) 2007
                            Infineon Technologies AG
                     Am Campeon 1-12; 81726 Munich, Germany

  THE DELIVERY OF THIS SOFTWARE AS WELL AS THE HEREBY GRANTED NON-EXCLUSIVE,
  WORLDWIDE LICENSE TO USE, COPY, MODIFY, DISTRIBUTE AND SUBLICENSE THIS
  SOFTWARE IS FREE OF CHARGE.

  THE LICENSED SOFTWARE IS PROVIDED "AS IS" AND INFINEON EXPRESSLY DISCLAIMS
  ALL REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING
  WITHOUT LIMITATION, WARRANTIES OR REPRESENTATIONS OF WORKMANSHIP,
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, DURABILITY, THAT THE
  OPERATING OF THE LICENSED SOFTWARE WILL BE ERROR FREE OR FREE OF ANY THIRD
  PARTY CLAIMS, INCLUDING WITHOUT LIMITATION CLAIMS OF THIRD PARTY INTELLECTUAL
  PROPERTY INFRINGEMENT.

  EXCEPT FOR ANY LIABILITY DUE TO WILFUL ACTS OR GROSS NEGLIGENCE AND EXCEPT
  FOR ANY PERSONAL INJURY INFINEON SHALL IN NO EVENT BE LIABLE FOR ANY CLAIM
  OR DAMAGES OF ANY KIND, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.

******************************************************************************/

/** LL Interface version, major number */
#define DRV_TAPI_LL_IF_VER_MAJOR      1
/** LL Interface version, minor number */
#define DRV_TAPI_LL_IF_VER_MINOR      2
/** LL Interface version, build number */
#define DRV_TAPI_LL_IF_VER_STEP       1
/** LL Interface version, package type */
#define DRV_TAPI_LL_IF_VER_TYPE       1

/* some ll device drivers use the short define, so we define some alias */
#define LL_IF_MAJORSTEP             DRV_TAPI_LL_IF_VER_MAJOR
#define LL_IF_MINORSTEP             DRV_TAPI_LL_IF_VER_MINOR
#define LL_IF_VERSIONSTEP           DRV_TAPI_LL_IF_VER_STEP
#define LL_IF_VERS_TYPE             DRV_TAPI_LL_IF_VER_TYPE

#endif /* _DRV_TAPI_LL_INTERFACE_VERSION_H */
