#!/bin/bash

#scp network root@192.168.2.124:/etc/cli/network
#scp system root@192.168.2.124:/etc/cli/system
scp cli root@192.168.2.124:/sbin/cli
scp help root@192.168.2.124:/etc/cli/help
#scp port root@192.168.2.124:/etc/cli/port
#scp services root@192.168.2.124:/etc/cli/services
scp auto_completion root@192.168.2.124:/etc/cli/auto_completion
scp services_vlan root@192.168.2.124:/etc/cli/services_vlan
#scp services_cos root@192.168.2.124:/etc/cli/services_cos
