#!/bin/sh

# создаем/обновляем папку в которой будет вся инфа о vlan
update_vlan_storage() {
	cat /proc/sys/net/dslam_sw/sw0/vid_table | while read line; do
		let "cnt=0"
		for word in $line; do
			case $cnt in
				0) num=$word;;
				1) eval "$word";;
				2) eval "$word";;
				*);;
			esac
			let "cnt=$cnt+1"
		done
		if [ "$VID" != "0" ]; then
			mkdir -p /etc/cli/vlans/$VID
			rm -f /etc/cli/vlans/$VID/ports
			for p in 0 `seq 15`; do
				let "tmp=(0x0$VLAN & (1 << $p))"
				if [ "$tmp" != "0" ]; then
					if [ "$p" -lt "8" ]; then
						# TODO: сделать проверку есть ли на этом порту ethernet модуль
						if [ -d "/sys/class/net/dsl0${p}/ms_private" ]; then
							echo "0/$p " >> /etc/cli/vlans/$VID/ports
						fi
					else
						# TODO: сделать проверку есть ли на этом порту ethernet модуль
						if [ -d "/sys/class/net/dsl1${p}/ms_private" ]; then
							echo "1/$(($p-8)) " >> /etc/cli/vlans/$VID/ports
						fi
					fi
				fi
			done
			let "tmp=(0x0$VLAN & (1 << 24))"
			if [ "$tmp" != "0" ]; then
				echo "ge0 " >> /etc/cli/vlans/$VID/ports
			fi
		fi
		
	done
	cat /proc/sys/net/dslam_sw/sw1/vid_table | while read line; do
		let "cnt=0"
		for word in $line; do
			case $cnt in
				0) num=$word;;
				1) eval "$word";;
				2) eval "$word";;
				*);;
			esac
			let "cnt=$cnt+1"
		done
		if [ "$VID" != "0" ]; then
			mkdir -p /etc/cli/vlans/$VID
			for p in 0 `seq 15`; do
				let "tmp=(0x0$VLAN & (1 << $p))"
				if [ "$tmp" != "0" ]; then
					if [ "$p" -lt "8" ]; then
						# TODO: сделать проверку есть ли на этом порту ethernet модуль
						if [ -d "/sys/class/net/dsl2${p}/ms_private" ]; then
							echo "2/$p " >> /etc/cli/vlans/$VID/ports
						fi
					else
						# TODO: сделать проверку есть ли на этом порту ethernet модуль
						if [ -d "/sys/class/net/dsl3${p}/ms_private" ]; then
							echo "3/$(($p-8)) " >> /etc/cli/vlans/$VID/ports
						fi
					fi
				fi
			done
			let "tmp=(0x0$VLAN & (1 << 24))"
			if [ "$tmp" != "0" ]; then
				echo "ge1 " >> /etc/cli/vlans/$VID/ports
			fi
		fi
	done
}

vlan_func() {
	prompt=":services:vlan"

	if [ "$vid" != "" ]; then
		vlan_vid_func $vid $*
	else

	case "$1" in
		"cd")
			shift
			cd_func $*
		;;
		"quit")
			exit 0
		;;
		"help" | "?")
			tab=1
			auto_completion
		;;
		"save")
			save_config
		;;
		"create")
			# создание vlan: create vlan_id N
			shift
			if [ "$1" != "vlan_id" ]; then
				echo "Syntax error, after create must be vlan_id <1-4095>"
				return
			fi
			shift
			if [ -d "/etc/cli/vlans/$1" ]; then
				echo "Vlan with VID=$1 already existed!"
				return
			fi
			
			if [ ! -d "/etc/cli/vlans" ]; then
				mkdir /etc/cli/vlans
			fi
			if [ -f "/etc/cli/vlans" ]; then
				vlans=`cat /etc/cli/vlans`
			else
				vlans=""
			fi
			for v in $vlans; do
				if [ "$1" = "$v" ]; then
					echo "Vlan with VID=$1 already existed!"
					return
				fi
			done
			echo " $1" >> /etc/cli/vlans
			echo "$1"
		;;
		"show")
			if [ -f "/etc/cli/vlans" ]; then
				vlans=`cat /etc/cli/vlans`
			else
				vlans=""
			fi
			for v in $vlans; do
				echo "Vlan id $v"
			done
			# выводим список всех созданных vlan
		;;
		"delete")
			# удаляем vlan: delete vlan_id N
		;;
		"")
		;;
		*)
			# тут надо проверять что у нас vid или имя vlan
			echo "Syntax error"
		;;
	esac
	
	fi

}
