#!/bin/bash

# PARAMS:
# 1 - current dist dir
# 2 - linux kernel path
# 3 - prefix

echo CONFIGURE AND BUILD DAA...
cd $1/daa
	conf_options="\
		--build=i686-linux-gnu \
		--host=mipsel-linux-uclibc \
		--disable-apoh \
		--disable-duslicincl \
		--disable-dxtincl \
		--enable-warnings \
		--enable-vineticincl=$1/vinetic/include \
		--enable-tapiincl=$1/tapi/include \
		--enable-kernelincl=$1/linux/include \
		--enable-boardname=SG4V22 \
		--prefix=$3
		"
	make clean
	aclocal
	automake --foreign
	./configure  $conf_options
	cp ./drv_config.h ./src
	cp ./drv_daa_version.h ./src
	make && make install

echo CONFIGURE AND BUILD VINETIC...
cd $1/vinetic
	conf_options="\
		--build=i686-linux-gnu \
		--host=mipsel-linux-uclibc \
		--enable-linux-26 \
		--enable-trace \
		--enable-debug \
		--enable-warnings \
		--enable-2cpe \
		--enable-lt \
		--disable-v1 \
		--disable-fax \
		--with-max-devices=4 \
		--with-access-mode=INTEL_MUX \
		--with-access-width=8 \
		--enable-kernelincl=$1/linux/include \
		--enable-tapiincl=$1/tapi/include \
		--prefix=$3
		"
	make clean
	aclocal
	automake --foreign
	./configure  $conf_options
	make && make install


echo CONFIGURE AND BUILD TAPI...
cd $1/tapi
	conf_options="\
		--build=i686-linux-gnu \
		--host=mipsel-linux-uclibc \
		--enable-linux-26 \
		--enable-trace \
		--enable-debug \
		--enable-warnings \
		--enable-2cpe \
		--enable-voice \
		--enable-dtmf \
		--enable-cid \
		--enable-lt \
		--enable-dect \
		--disable-fax \ --disable-v1 \
		--enable-kernelincl=$1/linux/include \
		--prefix=$3
		"
	make clean
	aclocal
	automake --foreign
	./configure  $conf_options
	make && make install


echo CONFIGURE AND BUILD SGATAB...
	cd $1/sgatab
	CC=mipsel-linux-gcc make -w -C $1/linux M=$1/sgatab modules
	cp $1/sgatab/drv_sgatab.ko $3/bin

