#!/bin/bash

# PARAMS:
# 1 - current dist dir
# 2 - linux kernel path

echo MAKING links...

ln -snf $1/drv_daa-1.0.2.0 		$1/daa
ln -snf $1/drv_sgatab-1.0.1 		$1/sgatab
ln -snf $1/drv_tapi-3.6.1 		$1/tapi
ln -snf $1/drv_vinetic-1.3.1_tapi-3.6.1 $1/vinetic
ln -snf $1/svinit-0.1 			$1/svinit
ln -snf $1/svd-0.1 			$1/svd

ln -snf $2 				$1/linux



echo PATCHING ALL...

cd $1/daa
patch -p1 < $1/daa.patch

cd $1/tapi
patch -p1 < $1/tapi.patch

cd $1/vinetic
patch -p1 < $1/vinetic.patch

