#!/bin/sh
# insert adm5120 module
if [ "`kdb get sys_dslam_hose`" = "1" ]; then
	modprobe adm5120sw dslam_hose=1
else
	modprobe adm5120sw
fi

# if DSL <--> Ethernet is on
MAPCFG=/etc/dsl2eth/dsl2eth.map
[ -f "$MAPCFG" ] || exit 0

tmp=`grep eth $MAPCFG`
[ -n "$tmp" ] || exit 0

for i in $tmp; do
    tmp2=`echo $i | grep eth`
    if [ -n "$tmp2" ]; then
        if [ -f "/proc/sys/net/adm5120sw/force_lnk_down_$i" ]; then
    	    echo 1 > /proc/sys/net/adm5120sw/force_lnk_down_$i
        fi
    fi
done
