#!/bin/sh
# Link Dependences between OS interfaces
# This script needs MAP-file (/etc/link_deps/link.map)
# which specifies what interface forces down other
# Example:
#	dsl0 E1_1 
# means that when dsl0 goes down E1_1 should go down too
# Each interface have it's own GO DOWN mean
#	 
# Written 2007 by Artem Y. Polyakov
#
#---------------------------------------------------------

CONFIG_NAME=/etc/linkdeps/link.map
sif=$1
lstate=$2

[ -f "${CONFIG_NAME}" ] || exit 0

tmp=`grep $sif $CONFIG_NAME`
[ -n "$tmp" ] || exit -1
set $tmp

if [ $# -ne "2" ]; then
    # configuration file syntax error
    exit 0;
fi

dif=$2
case $dif in
eth*)
	[ -f "/proc/sys/net/adm5120sw/force_lnk_down_$dif" ] || exit -1
	if [ "$lstate" -eq "0" ]; then
	    echo 1 >  /proc/sys/net/adm5120sw/force_lnk_down_$dif
	else
	    echo 0 >  /proc/sys/net/adm5120sw/force_lnk_down_$dif
	fi
	;;
E1*)
	ctrl_file="/sys/class/net/$dif/hw_private/force_link_down"
	[ -f "$ctrl_file" ] || exit -1
	if [ "$lstate" -eq "0" ]; then
	    echo 1 > $ctrl_file
#		echo `date`": Setup $dif 1 > $ctrl_file" >> /root/link_dep.log
	else
	    echo 0 > $ctrl_file
#		echo `date`": Setup $dif 0 > $ctrl_file" >> /root/link_dep.log
	fi
	;;
esac

