TARGET_CFLAGS += -I$(STAGING_DIR)/usr/include -I$(STAGING_DIR)/include $(TARGET_CFLAGS)
TARGET_CFLAGS += -L$(STAGING_DIR)/usr/lib     -L$(STAGING_DIR)/lib

TARGET_CONFIGURE_OPTS +=   CFLAGS="$(TARGET_CFLAGS)"
TARGET_CONFIGURE_OPTS += CPPFLAGS="-I$(STAGING_DIR)/usr/include -I$(STAGING_DIR)/include"
TARGET_CONFIGURE_OPTS +=  LDFLAGS="-L$(STAGING_DIR)/usr/lib     -L$(STAGING_DIR)/lib"
